package main

import "strings"

// Template for Pydantic model
const modelTemplate = `# DO NOT EDIT. Generated by protoc-gen-pydantic.
{{- $config := .Config -}}
{{- $hasAnyEnums := .HasAnyEnums -}}
{{- $customOptionFields := .CustomOptionFields -}}
{{- if .File.LeadingComments }}
"""
{{- range .File.LeadingComments }}
{{ . }}
{{- end }}
"""
{{- end }}
{{ if .StdImports._Enum }}
from enum import Enum as _Enum
{{- end }}
{{- if $hasAnyEnums }}
from dataclasses import dataclass as _dataclass
{{- end }}
{{- if .TypingImportLine }}
{{ .TypingImportLine }}
{{- end }}
{{- if .PydanticImportLine }}

{{ .PydanticImportLine }}
{{- end }}
{{- if .RuntimeImportLine }}

{{ .RuntimeImportLine }}
{{- end }}
{{- range .RelativeImports }}

{{ . }}
{{- end }}
{{- range .ExternalImports }}

{{ . }}
{{- end }}
{{- if .StdImports._BaseModel }}


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)
{{- end }}
{{- if $hasAnyEnums }}


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
{{- range $customOptionFields }}
    {{ .Name }}: {{ if $config.UseNoneUnionSyntaxInsteadOfOptional }}{{ .PythonType }} | None{{ else }}_Optional[{{ .PythonType }}]{{ end }} = None
{{- end }}


class _ProtoEnum({{ if $config.UseIntegersForEnums }}int{{ else }}str{{ end }}, _Enum):
    number: int
    _options_: _EnumValueOptions

{{- if $config.UseIntegersForEnums }}

    def __new__(cls, value: int, options: {{ if $config.UseNoneUnionSyntaxInsteadOfOptional }}_EnumValueOptions | None{{ else }}_Optional[_EnumValueOptions]{{ end }} = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        obj.number = int(value)
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj
{{- else }}

    def __new__(
        cls,
        value: str,
        number: int = 0,
        options: {{ if $config.UseNoneUnionSyntaxInsteadOfOptional }}_EnumValueOptions | None{{ else }}_Optional[_EnumValueOptions]{{ end }} = None,
    ):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.number = number
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj
{{- end }}

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_
{{- end }}
{{- range .Enums }}


{{template "renderEnum" (dict "Enum" . "Indent" "" "Config" $config "CustomOptionFields" $customOptionFields)}}{{- end }}{{- range .Messages }}


{{template "renderMessage" (dict "Message" . "Indent" "" "Config" $config "CustomOptionFields" $customOptionFields)}}{{- end -}}
{{- range .File.TrailingComments }}
# {{ . }}
{{- end }}
{{define "renderEnum" -}}
{{- $e := index . "Enum" -}}
{{- $indent := index . "Indent" -}}
{{- $bi := printf "%s    " $indent -}}
{{- $config := index . "Config" -}}
{{- $customOptionFields := index . "CustomOptionFields" -}}
{{$indent}}class {{ $e.Name }}(_ProtoEnum):
{{- if $e.LeadingComments }}
{{$bi}}"""
{{- range $e.LeadingComments }}
{{$bi}}{{ . }}
{{- end }}
{{$bi}}"""
{{- end }}
{{- if $e.TrailingComments }}
{{$bi}}{{ range $e.TrailingComments }}
{{$bi}}# {{ . }}
{{- end }}
{{- end }}
{{- range $i, $_ := $e.Values }}
{{- if and (not $i) (or $e.LeadingComments $e.TrailingComments)}}
{{$bi}}{{end}}{{- range .LeadingComments }}
{{$bi}}# {{ . }}
{{- end }}
{{- if $config.UseIntegersForEnums }}
{{- if .HasValueOptions }}
{{- if .SortedCustomOptions }}
{{$bi}}{{ .Name }} = (
{{$bi}}    {{ .Number }},
{{$bi}}    _EnumValueOptions(
{{- if .Deprecated }}
{{$bi}}        deprecated=True,
{{- end }}
{{- if .DebugRedact }}
{{$bi}}        debug_redact=True,
{{- end }}
{{- range .SortedCustomOptions }}
{{$bi}}        {{ .Key }}={{ .Value }},
{{- end }}
{{$bi}}    ),
{{$bi}})
{{- else }}
{{$bi}}{{ .Name }} = (
{{$bi}}    {{ .Number }},
{{$bi}}    _EnumValueOptions({{ if .Deprecated }}deprecated=True{{ end }}{{ if and .Deprecated .DebugRedact }}, {{ end }}{{ if .DebugRedact }}debug_redact=True{{ end }}),
{{$bi}})
{{- end }}
{{- else }}
{{$bi}}{{ .Name }} = {{ .Number }}
{{- end }}
{{- else }}
{{- if .HasValueOptions }}
{{- if .SortedCustomOptions }}
{{$bi}}{{ .Name }} = (
{{$bi}}    "{{ .Name }}",
{{$bi}}    {{ .Number }},
{{$bi}}    _EnumValueOptions(
{{- if .Deprecated }}
{{$bi}}        deprecated=True,
{{- end }}
{{- if .DebugRedact }}
{{$bi}}        debug_redact=True,
{{- end }}
{{- range .SortedCustomOptions }}
{{$bi}}        {{ .Key }}={{ .Value }},
{{- end }}
{{$bi}}    ),
{{$bi}})
{{- else }}
{{$bi}}{{ .Name }} = (
{{$bi}}    "{{ .Name }}",
{{$bi}}    {{ .Number }},
{{$bi}}    _EnumValueOptions({{ if .Deprecated }}deprecated=True{{ end }}{{ if and .Deprecated .DebugRedact }}, {{ end }}{{ if .DebugRedact }}debug_redact=True{{ end }}),
{{$bi}})
{{- end }}
{{- else }}
{{$bi}}{{ .Name }} = ("{{ .Name }}", {{ .Number }})
{{- end }}
{{- end }}
{{- range .TrailingComments }}
{{$bi}}# {{ . }}
{{- end }}
{{- end }}
{{- end -}}
{{define "renderMessage" -}}
{{- $m := index . "Message" -}}
{{- $indent := index . "Indent" -}}
{{- $bi := printf "%s    " $indent -}}
{{- $config := index . "Config" -}}
{{- $customOptionFields := index . "CustomOptionFields" -}}
{{$indent}}class {{ $m.Name }}(_ProtoModel):
{{- if $m.LeadingComments }}
{{$bi}}"""
{{- range $m.LeadingComments }}
{{$bi}}{{ . }}
{{- end }}
{{$bi}}"""{{- end }}
{{- if and $m.LeadingComments $m.HasAlias }}
{{ end }}{{- if $m.HasAlias }}
{{$bi}}model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())
{{- end }}
{{- if and (or $m.LeadingComments $m.HasAlias) $m.NestedEnums }}
{{ end }}{{- range $i, $e := $m.NestedEnums }}{{ if $i }}
{{ end }}
{{template "renderEnum" (dict "Enum" $e "Indent" $bi "Config" $config "CustomOptionFields" $customOptionFields)}}{{- end }}{{- if and (or $m.LeadingComments $m.HasAlias $m.NestedEnums) $m.NestedMessages }}
{{ end }}{{- range $i, $nm := $m.NestedMessages }}{{ if $i }}
{{ end }}
{{template "renderMessage" (dict "Message" $nm "Indent" $bi "Config" $config "CustomOptionFields" $customOptionFields)}}{{- end }}
{{- range $i, $v := $m.TrailingComments }}{{ if eq $i 0 }}
{{ end }}
{{$bi}}# {{ $v }}
{{- end }}
{{- if or $m.LeadingComments $m.HasAlias $m.NestedEnums $m.NestedMessages $m.TrailingComments }}
{{ end }}{{- range $field := $m.Fields }}
{{- range $field.LeadingComments }}
{{$bi}}# {{ . }}
{{- end }}
{{- if or (and (not $config.DisableFieldDescription) (or (ne (len $field.LeadingComments) 0) (ne $field.OneOf nil))) $field.Alias $field.IsDefaultFactory $field.HasConstraintKwargs ($field.NeedsMultilineDefault $bi) }}
{{- if $field.NeedsParenAssignment $bi }}
{{$bi}}{{ $field.Name }}: {{ $field.TypeAnnotationFormatted $bi }} = (
{{$bi}}    _Field(
{{- if $field.Default }}
{{$bi}}        {{ $field.Default }},
{{- end }}
{{- if and (not $config.DisableFieldDescription) (or (ne (len $field.LeadingComments) 0) (ne $field.OneOf nil)) }}
{{$bi}}        description={{ pyQuote $field.Description }},
{{- end }}
{{- if $field.Alias }}
{{$bi}}        alias="{{ $field.Alias }}",
{{- end }}
{{- range $field.ConstraintArgs }}
{{$bi}}        {{ . }},
{{- end }}
{{- range $field.DroppedConstraintComments }}
{{$bi}}        {{ . }}
{{- end }}
{{$bi}}    )
{{$bi}})
{{- else }}
{{$bi}}{{ $field.Name }}: {{ $field.TypeAnnotationFormatted $bi }} = _Field(
{{- if $field.Default }}
{{$bi}}    {{ $field.Default }},
{{- end }}
{{- if and (not $config.DisableFieldDescription) (or (ne (len $field.LeadingComments) 0) (ne $field.OneOf nil)) }}
{{$bi}}    description={{ pyQuote $field.Description }},
{{- end }}
{{- if $field.Alias }}
{{$bi}}    alias="{{ $field.Alias }}",
{{- end }}
{{- range $field.ConstraintArgs }}
{{$bi}}    {{ . }},
{{- end }}
{{- range $field.DroppedConstraintComments }}
{{$bi}}    {{ . }}
{{- end }}
{{$bi}})
{{- end }}
{{- else }}
{{$bi}}{{ $field.Name }}: {{ if $field.Default }}{{ $field.TypeAnnotationFormatted $bi }} = _Field({{ $field.Default }}){{ else }}{{ $field.TypeAnnotationFormattedBare $bi }}{{ end }}
{{- end }}
{{- range $field.TrailingComments }}
{{$bi}}# {{ . }}
{{- end }}{{- end }}{{- if $m.OneOfGroups }}
{{ end }}{{- range $oo := $m.OneOfGroups }}
{{$bi}}@_model_validator(mode="after")
{{$bi}}def _validate_oneof_{{ $oo.Name }}(self) -> "{{ $m.Name }}":
{{ pyOneofSetLine $bi $oo.FieldNames }}
{{$bi}}    if len(_set) > 1:
{{ pyRaiseOneof $bi $oo.Name }}
{{$bi}}    return self
{{- end }}
{{- if $m.CelValidators }}
{{ end }}{{- range $i, $cv := $m.CelValidators }}
{{ if gt $i 0 }}
{{ end }}{{$bi}}@_model_validator(mode="after")
{{$bi}}def _validate_cel_{{ $cv.RuleID }}(self) -> "{{ $m.Name }}":
{{- if $cv.ReturnsBool }}
{{ pycelCondLine $bi $cv.Expression }}
{{$bi}}        raise ValueError({{ pyQuote $cv.Message }})
{{- else }}
{{$bi}}    _cel_msg = {{ $cv.Expression }}
{{$bi}}    if _cel_msg:
{{$bi}}        raise ValueError(_cel_msg)
{{- end }}
{{$bi}}    return self
{{- end }}
{{- range $comment := $m.DroppedCelConstraints }}
{{$bi}}# buf.validate: {{ $comment }}
{{- end }}
{{- if and (eq (len $m.Fields) 0) (eq (len $m.NestedEnums) 0) (eq (len $m.NestedMessages) 0) }}
{{$bi}}pass
{{- end }}
{{- end -}}
`

// protoTypesBaseFuncs contains the always-present base function bodies for
// _proto_types.py. It starts with two newlines so that when appended directly
// after the last import/assignment line (which ends with \n), the result has
// exactly two blank lines before the first function — satisfying ruff E302.
const protoTypesBaseFuncs = `

def _coerce_int(v):
    return int(v)


ProtoInt64 = _Annotated[
    int,
    _BeforeValidator(_coerce_int),
    _PlainSerializer(lambda v: str(v), return_type=str, when_used="json"),
]

ProtoUInt64 = _Annotated[
    int,
    _BeforeValidator(_coerce_int),
    _PlainSerializer(lambda v: str(v), return_type=str, when_used="json"),
]


def _parse_timestamp(v):
    if isinstance(v, str):
        return _datetime.datetime.fromisoformat(v.replace("Z", "+00:00"))
    if isinstance(v, _datetime.datetime):
        return v
    raise ValueError(f"Cannot parse timestamp from {type(v)}")


def _serialize_timestamp(v):
    if v.tzinfo is None:
        v = v.replace(tzinfo=_datetime.timezone.utc)
    s = v.strftime("%Y-%m-%dT%H:%M:%S")
    us = v.microsecond
    if us:
        s += f".{us:06d}".rstrip("0")
    return s + "Z"


ProtoTimestamp = _Annotated[
    _datetime.datetime,
    _BeforeValidator(_parse_timestamp),
    _PlainSerializer(_serialize_timestamp, return_type=str, when_used="json"),
]


def _parse_duration(v):
    if isinstance(v, str):
        m = _re.match(r"^(-?\d+(?:\.\d+)?)s$", v)
        if not m:
            raise ValueError(f"Invalid duration: {v}")
        return _datetime.timedelta(seconds=float(m.group(1)))
    if isinstance(v, _datetime.timedelta):
        return v
    raise ValueError(f"Cannot parse duration from {type(v)}")


def _serialize_duration(v):
    total = v.total_seconds()
    if total == int(total):
        return f"{int(total)}s"
    return f"{total}s"


ProtoDuration = _Annotated[
    _datetime.timedelta,
    _BeforeValidator(_parse_duration),
    _PlainSerializer(_serialize_duration, return_type=str, when_used="json"),
]


def _require_unique(v):
    if len(v) != len(set(v)):
        raise ValueError("list items must be unique")
    return v


def _make_in_validator(valid_values):
    def _validate(v):
        if v not in valid_values:
            raise ValueError(f"value must be one of {sorted(valid_values)}")
        return v

    return _validate


def _make_not_in_validator(excluded_values):
    def _validate(v):
        if v in excluded_values:
            raise ValueError(f"value must not be one of {sorted(excluded_values)}")
        return v

    return _validate


def _make_cel_validator(pred, message: str):
    def _validate(v):
        if not pred(v):
            raise ValueError(message)
        return v

    return _validate


def _make_cel_str_validator(fn):
    def _validate(v):
        msg = fn(v)
        if msg:
            raise ValueError(msg)
        return v

    return _validate


def _is_unique(v) -> bool:
    return len(v) == len(set(v))


def _cel_matches(pattern: str, s: str) -> bool:
    return bool(_re.search(pattern, s))
`

// Each per-validator constant starts with two newlines so that when appended
// after content that ends with \n, the result has exactly two blank lines
// before the function definition (ruff E302).

const protoTypesEmailFunc = `

def _validate_email(v: str) -> str:
    if not v:
        return v
    from pydantic.networks import validate_email as _pydantic_validate_email

    _pydantic_validate_email(v)
    return v
`

const protoTypesURIFunc = `

def _validate_uri(v: str) -> str:
    if not v:
        return v
    _url_adapter.validate_python(v)
    return v
`

const protoTypesIPFunc = `

def _validate_ip(v: str) -> str:
    if not v:
        return v
    _ipaddress.ip_address(v)
    return v
`

const protoTypesIPv4Func = `

def _validate_ipv4(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv4Address(v)
    return v
`

const protoTypesIPv6Func = `

def _validate_ipv6(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv6Address(v)
    return v
`

const protoTypesUUIDFunc = `

def _validate_uuid(v: str) -> str:
    if not v:
        return v
    _uuid_lib.UUID(v)
    return v
`

const protoTypesFiniteFunc = `

def _require_finite(v: float) -> float:
    if not _math.isfinite(v):
        raise ValueError("value must be finite")
    return v
`

const protoTypesConstValidatorFunc = `

def _make_const_validator(c):
    def _validate(v):
        if v != c:
            raise ValueError(f"value must equal {c!r}")
        return v

    return _validate
`

const protoTypesHostnameFunc = `

def _validate_hostname(v: str) -> str:
    if not v:
        return v
    if len(v) > 253:
        raise ValueError("invalid hostname: too long")
    labels = v.rstrip(".").split(".")
    for label in labels:
        if not label or len(label) > 63:
            raise ValueError("invalid hostname: label length")
        if label.startswith("-") or label.endswith("-"):
            raise ValueError("invalid hostname: label has leading/trailing hyphen")
        if not _re.fullmatch(r"[A-Za-z0-9-]+", label):
            raise ValueError("invalid hostname: invalid characters")
    if labels[-1].isdigit():
        raise ValueError("invalid hostname: TLD is all-numeric")
    return v
`

const protoTypesURIRefFunc = `

def _validate_uri_ref(v: str) -> str:
    if not v:
        return v
    if _re.search(r"[\x00-\x1f\x7f\s]", v):
        raise ValueError(
            "invalid URI reference: contains control characters or whitespace"
        )
    return v
`

const protoTypesAddressFunc = `

def _validate_address(v: str) -> str:
    if not v:
        return v
    try:
        _ipaddress.ip_address(v)
        return v
    except ValueError:
        pass
    return _validate_hostname(v)
`

const protoTypesTUUIDFunc = `

def _validate_tuuid(v: str) -> str:
    if not v:
        return v
    if not _re.fullmatch(r"[0-9a-fA-F]{32}", v):
        raise ValueError("invalid trimmed UUID: must be 32 hex characters")
    return v
`

const protoTypesULIDFunc = `

def _validate_ulid(v: str) -> str:
    if not v:
        return v
    if len(v) != 26:
        raise ValueError("invalid ULID: must be 26 characters")
    if not _re.fullmatch(r"[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}", v):
        raise ValueError("invalid ULID: invalid characters")
    if v[0].upper() > "7":
        raise ValueError("invalid ULID: timestamp overflow")
    return v
`

const protoTypesIPWithPrefixlenFunc = `

def _validate_ip_with_prefixlen(v: str) -> str:
    if not v:
        return v
    _ipaddress.ip_interface(v)
    return v
`

const protoTypesIPv4WithPrefixlenFunc = `

def _validate_ipv4_with_prefixlen(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv4Interface(v)
    return v
`

const protoTypesIPv6WithPrefixlenFunc = `

def _validate_ipv6_with_prefixlen(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv6Interface(v)
    return v
`

const protoTypesIPPrefixFunc = `

def _validate_ip_prefix(v: str) -> str:
    if not v:
        return v
    _ipaddress.ip_network(v, strict=True)
    return v
`

const protoTypesIPv4PrefixFunc = `

def _validate_ipv4_prefix(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv4Network(v, strict=True)
    return v
`

const protoTypesIPv6PrefixFunc = `

def _validate_ipv6_prefix(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv6Network(v, strict=True)
    return v
`

const protoTypesHostAndPortFunc = `

def _validate_host_and_port(v: str) -> str:
    if not v:
        return v
    if v.startswith("["):
        end = v.find("]")
        if end == -1:
            raise ValueError("invalid host_and_port: unmatched '['")
        host = v[1:end]
        rest = v[end + 1 :]
        if not rest.startswith(":"):
            raise ValueError("invalid host_and_port: missing port after ']'")
        port_str = rest[1:]
        _ipaddress.IPv6Address(host)
    else:
        colon = v.rfind(":")
        if colon == -1:
            raise ValueError("invalid host_and_port: missing port")
        host, port_str = v[:colon], v[colon + 1 :]
        try:
            _ipaddress.IPv4Address(host)
        except ValueError:
            _validate_hostname(host)
    if not port_str.isdigit() or not 0 <= int(port_str) <= 65535:
        raise ValueError(f"invalid port: {port_str!r}")
    return v
`

const protoTypesHTTPHeaderNameFunc = `

def _validate_http_header_name(v: str) -> str:
    if not v:
        return v
    if not _re.fullmatch(r"[!#$%&'*+\-.^_` + "`" + `|~0-9A-Za-z]+", v):
        raise ValueError("invalid HTTP header name")
    return v
`

const protoTypesHTTPHeaderValueFunc = `

def _validate_http_header_value(v: str) -> str:
    if not v:
        return v
    if not _re.fullmatch(r"[\t\x20-\x7e]*", v):
        raise ValueError("invalid HTTP header value")
    return v
`

const protoTypesBytesUUIDFunc = `

def _validate_bytes_uuid(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) != 16:
        raise ValueError("invalid UUID bytes: must be exactly 16 bytes")
    return v
`

const protoTypesBytesIPFunc = `

def _validate_bytes_ip(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) not in (4, 16):
        raise ValueError("invalid IP bytes: must be 4 bytes (IPv4) or 16 bytes (IPv6)")
    return v
`

const protoTypesBytesIPv4Func = `

def _validate_bytes_ipv4(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) != 4:
        raise ValueError("invalid IPv4 bytes: must be exactly 4 bytes")
    return v
`

const protoTypesBytesIPv6Func = `

def _validate_bytes_ipv6(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) != 16:
        raise ValueError("invalid IPv6 bytes: must be exactly 16 bytes")
    return v
`

const protoTypesNotContainsFunc = `

def _make_not_contains_validator(s):
    def _validate(v):
        if s in v:
            raise ValueError(f"value must not contain {s!r}")
        return v

    return _validate
`

const protoTypesMinBytesFunc = `

def _make_min_bytes_validator(n):
    def _validate(v):
        b = v.encode()
        if len(b) < n:
            raise ValueError(f"value must be at least {n} bytes, got {len(b)} bytes")
        return v

    return _validate
`

const protoTypesMaxBytesFunc = `

def _make_max_bytes_validator(n):
    def _validate(v):
        b = v.encode()
        if len(b) > n:
            raise ValueError(f"value must be at most {n} bytes, got {len(b)} bytes")
        return v

    return _validate
`

const protoTypesLenBytesFunc = `

def _make_len_bytes_validator(n):
    def _validate(v):
        b = v.encode()
        if len(b) != n:
            raise ValueError(f"value must be exactly {n} bytes, got {len(b)} bytes")
        return v

    return _validate
`

// CEL bool-returning helper functions emitted conditionally by
// buildProtoTypesContent when CEL expressions use the corresponding is*()
// protovalidate functions.

const protoTypesCELIsEmailFunc = `

def _is_email(v: str) -> bool:
    if not v:
        return False
    try:
        from pydantic.networks import validate_email as _pydantic_validate_email

        _pydantic_validate_email(v)
        return True
    except Exception:
        return False
`

const protoTypesCELIsIpFunc = `

def _is_ip(v: str, version: int) -> bool:
    if not v:
        return False
    try:
        if version == 4:
            _ipaddress.IPv4Address(v)
        elif version == 6:
            _ipaddress.IPv6Address(v)
        else:
            _ipaddress.ip_address(v)
        return True
    except ValueError:
        return False
`

const protoTypesCELIsIpPrefixFunc = `

def _is_ip_prefix(v: str, version: int, *, strict: bool = False) -> bool:
    if not v:
        return False
    try:
        if version == 4:
            _ipaddress.IPv4Network(v, strict=strict)
        elif version == 6:
            _ipaddress.IPv6Network(v, strict=strict)
        else:
            try:
                _ipaddress.IPv6Network(v, strict=strict)
                return True
            except ValueError:
                _ipaddress.IPv4Network(v, strict=strict)
        return True
    except ValueError:
        return False
`

const protoTypesCELIsHostnameFunc = `

def _is_hostname(v: str) -> bool:
    if not v:
        return False
    try:
        _validate_hostname(v)
        return True
    except ValueError:
        return False
`

const protoTypesCELIsUriFunc = `

def _is_uri(v: str) -> bool:
    if not v:
        return False
    try:
        _url_adapter.validate_python(v)
        return True
    except Exception:
        return False
`

const protoTypesCELIsUriRefFunc = `

def _is_uri_ref(v: str) -> bool:
    if not v:
        return False
    return not bool(_re.search(r"[\x00-\x1f\x7f\s]", v))
`

const protoTypesCELIsHostAndPortFunc = `

def _is_host_and_port(v: str, requires_port: bool) -> bool:
    if not v:
        return False
    try:
        _validate_host_and_port(v)
        return True
    except ValueError:
        if not requires_port:
            try:
                _validate_hostname(v)
                return True
            except ValueError:
                pass
            try:
                _ipaddress.ip_address(v)
                return True
            except ValueError:
                pass
        return False
`

const protoTypesCELIsNanFunc = `

def _is_nan(v: float) -> bool:
    return _math.isnan(v)
`

const protoTypesCELIsInfFunc = `

def _is_inf(v: float, direction: int = 0) -> bool:
    if not _math.isinf(v):
        return False
    if direction > 0:
        return v > 0
    if direction < 0:
        return v < 0
    return True
`

const protoTypesCELTsInTzFunc = `

def _cel_ts_in_tz(v: _datetime.datetime, tz: str) -> _datetime.datetime:
    if tz == "UTC":
        return v
    try:
        import zoneinfo as _zoneinfo
    except ImportError:
        from backports import zoneinfo as _zoneinfo  # type: ignore[no-redef]
    return v.astimezone(_zoneinfo.ZoneInfo(tz))
`

const protoTypesCELDurGetHoursFunc = `

def _cel_dur_get_hours(v: _datetime.timedelta) -> int:
    return (v.days * 86400 + v.seconds) // 3600
`

const protoTypesCELDurGetMinutesFunc = `

def _cel_dur_get_minutes(v: _datetime.timedelta) -> int:
    return (v.days * 86400 + v.seconds) // 60
`

const protoTypesCELDurGetSecondsFunc = `

def _cel_dur_get_seconds(v: _datetime.timedelta) -> int:
    return v.days * 86400 + v.seconds
`

const protoTypesCELDurGetMillisFunc = `

def _cel_dur_get_milliseconds(v: _datetime.timedelta) -> int:
    return v.days * 86400000 + v.seconds * 1000 + v.microseconds // 1000
`

const protoTypesCELNowFunc = `

def _cel_now() -> _datetime.datetime:
    return _datetime.datetime.now(tz=_datetime.timezone.utc)
`

const protoTypesCELDurationFunc = `

def _cel_duration(total_seconds: float) -> _datetime.timedelta:
    return _datetime.timedelta(seconds=total_seconds)
`

const protoTypesCELTimestampFunc = `

def _cel_timestamp(s: str) -> _datetime.datetime:
    return _datetime.datetime.fromisoformat(s.replace("Z", "+00:00"))
`

// buildProtoTypesContent assembles the content for _proto_types.py, including
// only the format validator functions (and their imports) that are actually
// used by files in the same output directory.
func buildProtoTypesContent(needed map[string]bool) string {
	needIP := needed["_validate_ip"] || needed["_validate_ipv4"] || needed["_validate_ipv6"] ||
		needed["_validate_ip_with_prefixlen"] || needed["_validate_ipv4_with_prefixlen"] ||
		needed["_validate_ipv6_with_prefixlen"] || needed["_validate_ip_prefix"] ||
		needed["_validate_ipv4_prefix"] || needed["_validate_ipv6_prefix"] ||
		needed["_validate_address"] || needed["_validate_host_and_port"] ||
		// CEL bool-returning variants also need ipaddress
		needed["_is_ip"] || needed["_is_ip_prefix"] || needed["_is_host_and_port"]
	needURI := needed["_validate_uri"] || needed["_is_uri"]
	// hostname is a dependency for address, host_and_port, and their bool variants.
	needHostnameAsDep := needed["_validate_address"] || needed["_validate_host_and_port"] ||
		needed["_is_hostname"] || needed["_is_host_and_port"]

	var b strings.Builder

	b.WriteString("# DO NOT EDIT. Generated by protoc-gen-pydantic.\n")

	// Stdlib imports (alphabetical).
	b.WriteString("import datetime as _datetime\n")
	if needIP {
		b.WriteString("import ipaddress as _ipaddress\n")
	}
	if needed["_require_finite"] || needed["_is_nan"] || needed["_is_inf"] {
		b.WriteString("import math as _math\n")
	}
	b.WriteString("import re as _re\n")
	if needed["_validate_uuid"] {
		b.WriteString("import uuid as _uuid_lib\n")
	}
	b.WriteString("from typing import Annotated as _Annotated\n")
	b.WriteString("\n")

	// Third-party imports (alphabetical within group).
	if needURI {
		b.WriteString("from pydantic import AnyUrl as _AnyUrl\n")
	}
	b.WriteString("from pydantic import BeforeValidator as _BeforeValidator\n")
	b.WriteString("from pydantic import PlainSerializer as _PlainSerializer\n")
	if needURI {
		b.WriteString("from pydantic import TypeAdapter as _TypeAdapter\n")
	}

	// Module-level declarations.
	if needURI {
		b.WriteString("\n_url_adapter = _TypeAdapter(_AnyUrl)\n")
	}

	// Always-present base functions.
	b.WriteString(protoTypesBaseFuncs)

	// Conditional format validator functions.
	if needed["_validate_email"] {
		b.WriteString(protoTypesEmailFunc)
	}
	if needURI {
		b.WriteString(protoTypesURIFunc)
	}
	if needed["_validate_ip"] {
		b.WriteString(protoTypesIPFunc)
	}
	if needed["_validate_ipv4"] {
		b.WriteString(protoTypesIPv4Func)
	}
	if needed["_validate_ipv6"] {
		b.WriteString(protoTypesIPv6Func)
	}
	if needed["_validate_uuid"] {
		b.WriteString(protoTypesUUIDFunc)
	}
	if needed["_require_finite"] {
		b.WriteString(protoTypesFiniteFunc)
	}
	if needed["_make_const_validator"] {
		b.WriteString(protoTypesConstValidatorFunc)
	}

	// New format validators (Tier 1 additions).
	// hostname must come before address and host_and_port (they call it internally).
	if needHostnameAsDep || needed["_validate_hostname"] {
		b.WriteString(protoTypesHostnameFunc)
	}
	if needed["_validate_uri_ref"] {
		b.WriteString(protoTypesURIRefFunc)
	}
	if needed["_validate_address"] {
		b.WriteString(protoTypesAddressFunc)
	}
	if needed["_validate_tuuid"] {
		b.WriteString(protoTypesTUUIDFunc)
	}
	if needed["_validate_ulid"] {
		b.WriteString(protoTypesULIDFunc)
	}
	if needed["_validate_ip_with_prefixlen"] {
		b.WriteString(protoTypesIPWithPrefixlenFunc)
	}
	if needed["_validate_ipv4_with_prefixlen"] {
		b.WriteString(protoTypesIPv4WithPrefixlenFunc)
	}
	if needed["_validate_ipv6_with_prefixlen"] {
		b.WriteString(protoTypesIPv6WithPrefixlenFunc)
	}
	if needed["_validate_ip_prefix"] {
		b.WriteString(protoTypesIPPrefixFunc)
	}
	if needed["_validate_ipv4_prefix"] {
		b.WriteString(protoTypesIPv4PrefixFunc)
	}
	if needed["_validate_ipv6_prefix"] {
		b.WriteString(protoTypesIPv6PrefixFunc)
	}
	if needed["_validate_host_and_port"] || needed["_is_host_and_port"] {
		b.WriteString(protoTypesHostAndPortFunc)
	}
	if needed["_validate_http_header_name"] {
		b.WriteString(protoTypesHTTPHeaderNameFunc)
	}
	if needed["_validate_http_header_value"] {
		b.WriteString(protoTypesHTTPHeaderValueFunc)
	}
	if needed["_validate_bytes_uuid"] {
		b.WriteString(protoTypesBytesUUIDFunc)
	}
	if needed["_validate_bytes_ip"] {
		b.WriteString(protoTypesBytesIPFunc)
	}
	if needed["_validate_bytes_ipv4"] {
		b.WriteString(protoTypesBytesIPv4Func)
	}
	if needed["_validate_bytes_ipv6"] {
		b.WriteString(protoTypesBytesIPv6Func)
	}
	if needed["_make_not_contains_validator"] {
		b.WriteString(protoTypesNotContainsFunc)
	}
	if needed["_make_min_bytes_validator"] {
		b.WriteString(protoTypesMinBytesFunc)
	}
	if needed["_make_max_bytes_validator"] {
		b.WriteString(protoTypesMaxBytesFunc)
	}
	if needed["_make_len_bytes_validator"] {
		b.WriteString(protoTypesLenBytesFunc)
	}

	// CEL bool-returning helpers (is* functions from protovalidate).
	if needed["_is_email"] {
		b.WriteString(protoTypesCELIsEmailFunc)
	}
	if needed["_is_ip"] {
		b.WriteString(protoTypesCELIsIpFunc)
	}
	if needed["_is_ip_prefix"] {
		b.WriteString(protoTypesCELIsIpPrefixFunc)
	}
	// _is_hostname depends on _validate_hostname already being emitted above.
	if needed["_is_hostname"] {
		b.WriteString(protoTypesCELIsHostnameFunc)
	}
	// _is_uri depends on _url_adapter already being emitted above.
	if needed["_is_uri"] {
		b.WriteString(protoTypesCELIsUriFunc)
	}
	if needed["_is_uri_ref"] {
		b.WriteString(protoTypesCELIsUriRefFunc)
	}
	// _is_host_and_port depends on _validate_host_and_port and _validate_hostname.
	if needed["_is_host_and_port"] {
		b.WriteString(protoTypesCELIsHostAndPortFunc)
	}
	if needed["_is_nan"] {
		b.WriteString(protoTypesCELIsNanFunc)
	}
	if needed["_is_inf"] {
		b.WriteString(protoTypesCELIsInfFunc)
	}
	if needed["_cel_now"] {
		b.WriteString(protoTypesCELNowFunc)
	}
	if needed["_cel_duration"] {
		b.WriteString(protoTypesCELDurationFunc)
	}
	if needed["_cel_timestamp"] {
		b.WriteString(protoTypesCELTimestampFunc)
	}
	if needed["_cel_ts_in_tz"] {
		b.WriteString(protoTypesCELTsInTzFunc)
	}
	if needed["_cel_dur_get_hours"] {
		b.WriteString(protoTypesCELDurGetHoursFunc)
	}
	if needed["_cel_dur_get_minutes"] {
		b.WriteString(protoTypesCELDurGetMinutesFunc)
	}
	if needed["_cel_dur_get_seconds"] {
		b.WriteString(protoTypesCELDurGetSecondsFunc)
	}
	if needed["_cel_dur_get_milliseconds"] {
		b.WriteString(protoTypesCELDurGetMillisFunc)
	}

	return b.String()
}
