# DO NOT EDIT. Generated by protoc-gen-pydantic.


from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from api.v1.types_pydantic import Message

from api.v1.types_pydantic import Foo


class CrossRefMessage(_BaseModel):
    """

    Attributes:
      id_ (str):
      referenced_message (Message):
      foo_list (list[Foo]):
    """

    model_config = _ConfigDict(
        populate_by_name=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    id_: "str" = _Field(..., alias="id")

    referenced_message: "Message" = _Field(...)

    foo_list: "list[Foo]" = _Field(...)
