# DO NOT EDIT. Generated by protoc-gen-pydantic.

from ._proto_types import _EnumValueOptions, _ProtoEnum


class Language(_ProtoEnum):
    """
    Language enum using custom options defined in another package.
    """

    LANGUAGE_UNSPECIFIED = 0
    LANGUAGE_PYTHON = (
        1,
        _EnumValueOptions(
            display_name="Python",
        ),
    )
    LANGUAGE_GOLANG = (
        2,
        _EnumValueOptions(
            display_name="Golang",
        ),
    )
    LANGUAGE_RUST = (
        3,
        _EnumValueOptions(
            display_name="Rust",
            priority=1,
        ),
    )
