# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass


@_dataclass(frozen=True)
class _EnumValueOptions:
    number: int
    deprecated: bool = False
    debug_redact: bool = False
    display_name: str | None = None
    is_default: bool | None = None
    priority: int | None = None


class _ProtoEnum(int, _Enum):
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _EnumValueOptions | None = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        if options is not None:
            obj._options_ = options
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Language(_ProtoEnum):
    """
    Language enum using custom options defined in another package.
    """

    LANGUAGE_UNSPECIFIED = (
        0,
        _EnumValueOptions(number=0),
    )  # LANGUAGE_UNSPECIFIED

    LANGUAGE_PYTHON = (
        1,
        _EnumValueOptions(
            number=1,
            display_name="Python",
        ),
    )  # LANGUAGE_PYTHON

    LANGUAGE_GOLANG = (
        2,
        _EnumValueOptions(
            number=2,
            display_name="Golang",
        ),
    )  # LANGUAGE_GOLANG

    LANGUAGE_RUST = (
        3,
        _EnumValueOptions(
            number=3,
            display_name="Rust",
            priority=1,
        ),
    )  # LANGUAGE_RUST
