# DO NOT EDIT. Generated by protoc-gen-pydantic.

from typing import Annotated as _Annotated

from pydantic import (
    AfterValidator as _AfterValidator,
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
)

from ._proto_types import _validate_email, _validate_uuid


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class ValidatedEmail(_ProtoModel):
    """
    ValidatedEmail exercises the string.email format constraint.

    Attributes:
      address (_Annotated[str, _AfterValidator(_validate_email)]):
        Address must be a valid email address.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Address must be a valid email address.
    address: "_Annotated[str, _AfterValidator(_validate_email)]" = _Field(
        "",
    )


class ValidatedUUID(_ProtoModel):
    """
    ValidatedUUID exercises the string.uuid format constraint.

    Attributes:
      id_ (_Annotated[str, _AfterValidator(_validate_uuid)]):
        Id must be a valid UUID.
    """

    model_config = _ConfigDict(
        populate_by_name=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Id must be a valid UUID.
    id_: "_Annotated[str, _AfterValidator(_validate_uuid)]" = _Field(
        "",
        alias="id",
    )
