# DO NOT EDIT. Generated by protoc-gen-pydantic.

from typing import Annotated as _Annotated

from pydantic import (
    AfterValidator as _AfterValidator,
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
)

from ._proto_types import _validate_email, _validate_uuid


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class ValidatedEmail(_ProtoModel):
    """
    ValidatedEmail exercises the string.email format constraint.
    """

    # Address must be a valid email address.
    address: _Annotated[str, _AfterValidator(_validate_email)]


class ValidatedUUID(_ProtoModel):
    """
    ValidatedUUID exercises the string.uuid format constraint.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Id must be a valid UUID.
    id_: _Annotated[str, _AfterValidator(_validate_uuid)] = _Field(
        alias="id",
    )
