# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class CommentedMessage(_ProtoModel):
    """
    Leading comment on CommentedMessage.
    CommentedMessage exercises all comment positions.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    class NestedEnum(_ProtoEnum):
        """
        Leading comment on NestedEnum.
        An enum nested inside CommentedMessage.
        """

        # Trailing comment on NestedEnum.
        # Documents the enum values.

        # Leading comment on UNSPECIFIED value.
        UNSPECIFIED = ("UNSPECIFIED", 0)
        # Right comment on UNSPECIFIED.
        # Leading comment on ACTIVE value.
        ACTIVE = ("ACTIVE", 1)
        # Right comment on ACTIVE.
        # Leading comment on INACTIVE value.
        INACTIVE = ("INACTIVE", 2)
        # Right comment on INACTIVE.

    class NestedMessage(_ProtoModel):
        """
        Leading comment on NestedMessage.
        A message nested inside CommentedMessage.
        """

        model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

        # Trailing comment on NestedMessage.
        # Documents internal structure.

        # Leading comment on nested first_name.
        # The given name in the nested message.
        first_name: str = _Field(
            default="",
            description="Leading comment on nested first_name.\nThe given name in the nested message.",
            alias="firstName",
        )
        # Right comment on nested first_name.
        # Leading comment on nested last_name.
        # The family name in the nested message.
        last_name: str = _Field(
            default="",
            description="Leading comment on nested last_name.\nThe family name in the nested message.",
            alias="lastName",
        )
        # Right comment on nested last_name.

    # Trailing comment on CommentedMessage.
    # Documents internal structure.

    # Leading comment on first_name.
    # The given name of the person.
    first_name: str = _Field(
        default="",
        description="Leading comment on first_name.\nThe given name of the person.",
        alias="firstName",
    )
    # Right comment on first_name.
    # Leading comment on last_name.
    # The family name of the person.
    last_name: str = _Field(
        default="",
        description="Leading comment on last_name.\nThe family name of the person.",
        alias="lastName",
    )
    # Right comment on last_name.


class Outer(_ProtoModel):
    """
    Outer message comment.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    class OuterEnum(_ProtoEnum):
        """
        Outer enum comment.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        X = ("X", 1)

    class Inner(_ProtoModel):
        """
        Inner message comment.
        """

        model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

        class InnerEnum(_ProtoEnum):
            """
            Inner enum comment.
            """

            UNSPECIFIED = ("UNSPECIFIED", 0)
            A = ("A", 1)

        class Deepest(_ProtoModel):
            """
            Deepest message comment.
            """

            model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

            # Deepest field comment.
            deepest_field: str = _Field(
                default="",
                description="Deepest field comment.",
                alias="deepestField",
            )

        # Inner field comment.
        inner_field: str = _Field(
            default="",
            description="Inner field comment.",
            alias="innerField",
        )

    # Outer field comment.
    outer_field: str = _Field(
        default="",
        description="Outer field comment.",
        alias="outerField",
    )
