# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    display_name: str | None = None
    is_default: bool | None = None
    priority: int | None = None
    rank: int | None = None
    rate: float | None = None
    serial: int | None = None
    version: int | None = None
    weight: float | None = None


class _ProtoEnum(str, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(
        cls,
        value: str,
        number: int = 0,
        options: _EnumValueOptions | None = None,
    ):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.number = number
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Currency(_ProtoEnum):
    """
    Currency enum with custom options.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    USD = (
        "USD",
        1,
        _EnumValueOptions(
            display_name="US Dollar",
            is_default=True,
            priority=1,
            rank=1,
            rate=1.5,
            serial=1000,
            version=1,
            weight=1,
        ),
    )
    EUR = (
        "EUR",
        2,
        _EnumValueOptions(
            display_name="Euro",
            is_default=False,
            priority=2,
        ),
    )
    GBP = (
        "GBP",
        3,
        _EnumValueOptions(
            display_name="British Pound",
        ),
    )


class Color(_ProtoEnum):
    """
    Color enum without custom options (regression test).
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    RED = ("RED", 1)
    GREEN = ("GREEN", 2)
    BLUE = ("BLUE", 3)
