# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import _EnumValueOptions, _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Enum(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    ACTIVE = ("ACTIVE", 1)
    INACTIVE = ("INACTIVE", 2)


class Hue(_ProtoEnum):
    """
    A primary hue.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    RED = ("RED", 1)
    BLUE = ("BLUE", 2)


class Shape(_ProtoModel):
    class Kind(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        CIRCLE = ("CIRCLE", 1)
        SQUARE = (
            "SQUARE",
            2,
            _EnumValueOptions(deprecated=True),
        )

    color: "Hue | None" = _Field(default=None)
    kind: "Shape.Kind | None" = _Field(default=None)
