# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Item(_ProtoModel):
    name: str = _Field(default="")
    quantity: int = _Field(default=0)
    price: float = _Field(default=0.0)


class Person(_ProtoModel):
    name: str = _Field(default="")
    age: int = _Field(default=0)
    active: bool = _Field(default=False)
    score: float = _Field(default=0.0)
    avatar: bytes = _Field(default=b"")


class SearchRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    query: str | None = _Field(default=None)
    page_size: int | None = _Field(
        default=None,
        alias="pageSize",
    )
    include_deleted: bool | None = _Field(
        default=None,
        alias="includeDeleted",
    )


class TaggedItem(_ProtoModel):
    name: str = _Field(default="")
    tags: list[str] = _Field(
        default_factory=list,
    )
    scores: list[int] = _Field(
        default_factory=list,
    )


class Config(_ProtoModel):
    labels: dict[str, str] = _Field(
        default_factory=dict,
    )
    counters: dict[str, int] = _Field(
        default_factory=dict,
    )


class Payment(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    credit_card: str | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["credit_card", "paypal", "bank_iban"] (oneof method)',
        alias="creditCard",
    )
    paypal: str | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["credit_card", "paypal", "bank_iban"] (oneof method)',
    )
    bank_iban: str | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["credit_card", "paypal", "bank_iban"] (oneof method)',
        alias="bankIban",
    )

    @_model_validator(mode="after")
    def _validate_oneof_method(self) -> "Payment":
        _set = [
            f
            for f in ("credit_card", "paypal", "bank_iban")
            if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(f"oneof 'method': only one field may be set, got {_set!r}")
        return self


class Address(_ProtoModel):
    street: str = _Field(default="")
    city: str = _Field(default="")


class Order(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    order_id: str = _Field(
        default="",
        alias="orderId",
    )
    address: "Address | None" = _Field(default=None)


class Task(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    class Status(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        OPEN = ("OPEN", 1)
        DONE = ("DONE", 2)

    status_label: str = _Field(
        default="",
        alias="statusLabel",
    )
    status: "Task.Status | None" = _Field(default=None)
