# DO NOT EDIT. Generated by protoc-gen-pydantic.
from typing import Any as _Any

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoDuration, ProtoInt64, ProtoTimestamp, ProtoUInt64


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class WellKnownTypes(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    wkt_timestamp: ProtoTimestamp | None = _Field(
        default=None,
        alias="wktTimestamp",
    )
    wkt_duration: ProtoDuration | None = _Field(
        default=None,
        alias="wktDuration",
    )
    wkt_struct: dict[str, _Any] | None = _Field(
        default=None,
        alias="wktStruct",
    )
    wkt_value: _Any | None = _Field(
        default=None,
        alias="wktValue",
    )
    wkt_list_value: list[_Any] | None = _Field(
        default=None,
        alias="wktListValue",
    )
    wkt_any: _Any | None = _Field(
        default=None,
        alias="wktAny",
    )
    wkt_field_mask: list[str] | None = _Field(
        default=None,
        alias="wktFieldMask",
    )
    wkt_bool: bool | None = _Field(
        default=None,
        alias="wktBool",
    )
    wkt_int32: int | None = _Field(
        default=None,
        alias="wktInt32",
    )
    wkt_int64: ProtoInt64 | None = _Field(
        default=None,
        alias="wktInt64",
    )
    wkt_uint32: int | None = _Field(
        default=None,
        alias="wktUint32",
    )
    wkt_uint64: ProtoUInt64 | None = _Field(
        default=None,
        alias="wktUint64",
    )
    wkt_float: float | None = _Field(
        default=None,
        alias="wktFloat",
    )
    wkt_double: float | None = _Field(
        default=None,
        alias="wktDouble",
    )
    wkt_string: str | None = _Field(
        default=None,
        alias="wktString",
    )
    wkt_bytes: bytes | None = _Field(
        default=None,
        alias="wktBytes",
    )
    wkt_empty: None = _Field(
        default=None,
        alias="wktEmpty",
    )


class Event(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    id_: str = _Field(
        default="",
        alias="id",
    )
    occurred: ProtoTimestamp | None = _Field(default=None)
    duration: ProtoDuration | None = _Field(default=None)
    metadata: dict[str, _Any] | None = _Field(default=None)
    update_mask: list[str] | None = _Field(
        default=None,
        alias="updateMask",
    )
    retry_count: int | None = _Field(
        default=None,
        alias="retryCount",
    )
