# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    display_name: str | None = None
    is_default: bool | None = None
    priority: int | None = None
    rank: int | None = None
    rate: float | None = None
    serial: int | None = None
    version: int | None = None
    weight: float | None = None


class _ProtoEnum(str, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(
        cls,
        value: str,
        number: int = 0,
        options: _EnumValueOptions | None = None,
    ):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.number = number
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Shipment(_ProtoModel):
    class Status(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        PENDING = ("PENDING", 1)
        SHIPPED = ("SHIPPED", 2)
        DELIVERED = ("DELIVERED", 3)

    class Item(_ProtoModel):
        sku: str = _Field(default="")
        quantity: int = _Field(default=0)
        price: float = _Field(default=0.0)

    order_id: str = _Field(default="")
    items: "list[Shipment.Item]" = _Field(
        default_factory=list,
    )
    status_note: str = _Field(default="")
    status: "Shipment.Status | None" = _Field(default=None)
