# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoInt64, ProtoUInt64, _ProtoEnum

from .enums_pydantic import Enum

from .messages_pydantic import Message


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Scalars(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    class NestedEnum(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        ACTIVE = ("ACTIVE", 1)
        INACTIVE = ("INACTIVE", 2)

    class NestedMessage(_ProtoModel):
        model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

        first_name: str = _Field(
            default="",
            alias="firstName",
        )
        last_name: str = _Field(
            default="",
            alias="lastName",
        )

    int32: int = _Field(default=0)
    int64: ProtoInt64 = _Field(default=0)
    uint32: int = _Field(default=0)
    uint64: ProtoUInt64 = _Field(default=0)
    fixed32: int = _Field(default=0)
    fixed64: ProtoUInt64 = _Field(default=0)
    sint32: int = _Field(default=0)
    sint64: ProtoInt64 = _Field(default=0)
    sfixed32: int = _Field(default=0)
    sfixed64: ProtoInt64 = _Field(default=0)
    bool_: bool = _Field(
        default=False,
        alias="bool",
    )
    float_: float = _Field(
        default=0.0,
        alias="float",
    )
    double: float = _Field(default=0.0)
    string: str = _Field(default="")
    bytes_: bytes = _Field(
        default=b"",
        alias="bytes",
    )
    enum: "Enum | None" = _Field(default=None)
    nested_enum: "Scalars.NestedEnum | None" = _Field(
        default=None,
        alias="nestedEnum",
    )
    message: "Message | None" = _Field(default=None)
    nested_message: "Scalars.NestedMessage | None" = _Field(
        default=None,
        alias="nestedMessage",
    )
    int32_optional: int | None = _Field(
        default=None,
        alias="int32Optional",
    )
    int64_optional: ProtoInt64 | None = _Field(
        default=None,
        alias="int64Optional",
    )
    uint32_optional: int | None = _Field(
        default=None,
        alias="uint32Optional",
    )
    uint64_optional: ProtoUInt64 | None = _Field(
        default=None,
        alias="uint64Optional",
    )
    fixed32_optional: int | None = _Field(
        default=None,
        alias="fixed32Optional",
    )
    fixed64_optional: ProtoUInt64 | None = _Field(
        default=None,
        alias="fixed64Optional",
    )
    sint32_optional: int | None = _Field(
        default=None,
        alias="sint32Optional",
    )
    sint64_optional: ProtoInt64 | None = _Field(
        default=None,
        alias="sint64Optional",
    )
    sfixed32_optional: int | None = _Field(
        default=None,
        alias="sfixed32Optional",
    )
    sfixed64_optional: ProtoInt64 | None = _Field(
        default=None,
        alias="sfixed64Optional",
    )
    bool_optional: bool | None = _Field(
        default=None,
        alias="boolOptional",
    )
    float_optional: float | None = _Field(
        default=None,
        alias="floatOptional",
    )
    double_optional: float | None = _Field(
        default=None,
        alias="doubleOptional",
    )
    string_optional: str | None = _Field(
        default=None,
        alias="stringOptional",
    )
    bytes_optional: bytes | None = _Field(
        default=None,
        alias="bytesOptional",
    )
    enum_optional: "Enum | None" = _Field(
        default=None,
        alias="enumOptional",
    )
    nested_enum_optional: "Scalars.NestedEnum | None" = _Field(
        default=None,
        alias="nestedEnumOptional",
    )
    message_optional: "Message | None" = _Field(
        default=None,
        alias="messageOptional",
    )
    nested_message_optional: "Scalars.NestedMessage | None" = _Field(
        default=None,
        alias="nestedMessageOptional",
    )
