# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import (
    ProtoDuration,
    ProtoInt64,
    ProtoTimestamp,
    ProtoUInt64,
    _ProtoEnum,
)


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class ValidatedScalars(_ProtoModel):
    """
    ValidatedScalars exercises numeric bound constraints.
    """

    # Age must be between 0 and 150 exclusive of 0.
    age: int = _Field(
        default=0,
        description="Age must be between 0 and 150 exclusive of 0.",
    )
    # Score must be in [0.0, 100.0].
    score: float = _Field(
        default=0.0,
        description="Score must be in [0.0, 100.0].",
    )
    # Priority must be positive.
    priority: ProtoInt64 = _Field(
        default=0,
        description="Priority must be positive.",
    )
    # Ratio must be non-negative and less than 1.
    ratio: float = _Field(
        default=0.0,
        description="Ratio must be non-negative and less than 1.",
    )
    # Rank must be in [1, 10].
    rank: int = _Field(
        default=0,
        description="Rank must be in [1, 10].",
    )
    # Count must be non-zero (covers uint64 / fixed64 literal formatting).
    count: ProtoUInt64 | None = _Field(
        default=None,
        description="Count must be non-zero (covers uint64 / fixed64 literal formatting).",
    )
    # Offset must be non-negative (covers sint32 / sfixed32 literal formatting).
    offset: int | None = _Field(
        default=None,
        description="Offset must be non-negative (covers sint32 / sfixed32 literal formatting).",
    )


class ValidatedStrings(_ProtoModel):
    """
    ValidatedStrings exercises string length and pattern constraints.
    """

    # Name must be between 1 and 100 characters.
    name: str = _Field(
        default="",
        description="Name must be between 1 and 100 characters.",
    )
    # Code must match uppercase letters only.
    code: str = _Field(
        default="",
        description="Code must match uppercase letters only.",
    )
    # Bio has only a max length.
    bio: str = _Field(
        default="",
        description="Bio has only a max length.",
    )
    # Tag has only a min length.
    tag: str = _Field(
        default="",
        description="Tag has only a min length.",
    )


class ValidatedRepeated(_ProtoModel):
    """
    ValidatedRepeated exercises repeated field length constraints.
    """

    # Items must have between 1 and 10 elements.
    items: list[str] = _Field(
        default_factory=list,
        description="Items must have between 1 and 10 elements.",
    )
    # Tags must have at least 1 element.
    tags: list[str] = _Field(
        default_factory=list,
        description="Tags must have at least 1 element.",
    )


class ValidatedMap(_ProtoModel):
    """
    ValidatedMap exercises map field length constraints.
    """

    # Labels must have between 1 and 10 entries.
    labels: dict[str, str] = _Field(
        default_factory=dict,
        description="Labels must have between 1 and 10 entries.",
    )


class ValidatedReserved(_ProtoModel):
    """
    ValidatedReserved exercises a field whose name is a Python reserved word and
    also carries a buf.validate constraint. The generated field must emit both
    alias= and the constraint kwargs in a single _Field() call.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Score must be positive.
    float_: float = _Field(
        default=0.0,
        description="Score must be positive.",
        alias="float",
    )


class ValidatedOneof(_ProtoModel):
    """
    ValidatedOneof exercises a oneof field that also carries a constraint.
    """

    # Must be positive when set.
    small: int | None = _Field(
        default=None,
        description='Must be positive when set.\nOnly one of the fields can be specified with: ["small", "large"] (oneof value)',
    )
    # Must be positive when set.
    large: ProtoInt64 | None = _Field(
        default=None,
        description='Must be positive when set.\nOnly one of the fields can be specified with: ["small", "large"] (oneof value)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_value(self) -> "ValidatedOneof":
        _set = [f for f in ("small", "large") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'value': only one field may be set, got {_set!r}")
        return self


class ValidatedDuration(_ProtoModel):
    """
    ValidatedDuration exercises Duration bound constraints, which use
    message-typed rule fields and cannot be translated to Pydantic Field() args.
    The generator must not panic; instead it emits dropped-constraint comments.
    """

    # Timeout must be positive and at most one hour.
    timeout: ProtoDuration | None = _Field(
        default=None,
        description="Timeout must be positive and at most one hour.",
    )


class ValidatedTimestamp(_ProtoModel):
    """
    ValidatedTimestamp exercises Timestamp bound constraints, which also use
    message-typed rule fields and must not panic.
    """

    # CreatedAt must be after the Unix epoch.
    created_at: ProtoTimestamp | None = _Field(
        default=None,
        description="CreatedAt must be after the Unix epoch.",
    )


class ValidatedStringLen(_ProtoModel):
    """
    ValidatedStringLen exercises the string.len exact-length constraint.
    """

    # Code must be exactly 5 characters.
    code: str = _Field(
        default="",
        description="Code must be exactly 5 characters.",
    )


class ValidatedStringAffix(_ProtoModel):
    """
    ValidatedStringAffix exercises string.prefix and string.suffix constraints.
    """

    # Url must start with "https://".
    url: str = _Field(
        default="",
        description='Url must start with "https://".',
    )
    # Filename must end with ".go".
    filename: str = _Field(
        default="",
        description='Filename must end with ".go".',
    )
    # Path must start with "/home/" and end with ".txt".
    path: str = _Field(
        default="",
        description='Path must start with "/home/" and end with ".txt".',
    )
    # Content must match a pattern; prefix is also set (conflict → prefix dropped).
    content: str = _Field(
        default="",
        description="Content must match a pattern; prefix is also set (conflict → prefix dropped).",
    )
    # Report must match a pattern; suffix is also set (conflict → suffix dropped).
    report: str = _Field(
        default="",
        description="Report must match a pattern; suffix is also set (conflict → suffix dropped).",
    )
    # Notes must match a pattern; contains is also set (conflict → contains dropped).
    notes: str = _Field(
        default="",
        description="Notes must match a pattern; contains is also set (conflict → contains dropped).",
    )


class ValidatedExamples(_ProtoModel):
    """
    ValidatedExamples exercises the field examples annotation.
    """

    # Count with integer examples.
    count: int = _Field(
        default=0,
        description="Count with integer examples.",
    )
    # Name with string examples.
    name: str = _Field(
        default="",
        description="Name with string examples.",
    )


class ValidatedFormats(_ProtoModel):
    """
    ValidatedFormats exercises format and semantic validators: email, URI,
    IP address (v4/v6), UUID, and float finite.
    """

    # Email must be a valid email address.
    email: str = _Field(
        default="",
        description="Email must be a valid email address.",
    )
    # Website must be a valid URI.
    website: str = _Field(
        default="",
        description="Website must be a valid URI.",
    )
    # Address must be a valid IP address.
    address: str = _Field(
        default="",
        description="Address must be a valid IP address.",
    )
    # Ratio must be finite (not inf or NaN).
    ratio: float = _Field(
        default=0.0,
        description="Ratio must be finite (not inf or NaN).",
    )
    # Token must be a valid UUID.
    token: str = _Field(
        default="",
        description="Token must be a valid UUID.",
    )
    # Host must be a valid IPv4 address.
    host_v4: str = _Field(
        default="",
        description="Host must be a valid IPv4 address.",
    )
    # Host must be a valid IPv6 address.
    host_v6: str = _Field(
        default="",
        description="Host must be a valid IPv6 address.",
    )


class ValidatedFinite(_ProtoModel):
    """
    ValidatedFinite exercises float.finite and double.finite constraints.
    """

    # Ratio must be finite (not inf or NaN).
    ratio: float = _Field(
        default=0.0,
        description="Ratio must be finite (not inf or NaN).",
    )
    # Value must be finite (not inf or NaN).
    value: float = _Field(
        default=0.0,
        description="Value must be finite (not inf or NaN).",
    )


class ValidatedDropped(_ProtoModel):
    """
    ValidatedDropped exercises constraints that are recognised but not translated.
    """

    # Name is required; the required constraint is not translated.
    name: str = _Field(
        default="",
        description="Name is required; the required constraint is not translated.",
    )
    # Blob has a bytes.const constraint which is not translated (bytes kind unsupported).
    blob: bytes = _Field(
        default=b"",
        description="Blob has a bytes.const constraint which is not translated (bytes kind unsupported).",
    )
    # Score must be positive; required is also set but not translated.
    score: int = _Field(
        default=0,
        description="Score must be positive; required is also set but not translated.",
    )


class ValidatedConst(_ProtoModel):
    """
    ValidatedConst exercises the const constraint translated to Literal[...].
    """

    tag: str = _Field(default="")
    count: int = _Field(default=0)
    active: bool = _Field(default=False)
    score: float = _Field(default=0.0)
    code: int = _Field(default=0)
    inactive: bool = _Field(default=False)


class ValidatedIn(_ProtoModel):
    """
    ValidatedIn exercises in and not_in constraints translated to AfterValidator.
    """

    status: str = _Field(default="")
    code: str = _Field(default="")
    priority: int = _Field(default=0)
    # Limit covers uint32.in (exercises the uint path in formatScalarLiteral).
    limit: int = _Field(
        default=0,
        description="Limit covers uint32.in (exercises the uint path in formatScalarLiteral).",
    )


class ValidatedUnique(_ProtoModel):
    """
    ValidatedUnique exercises repeated.unique translated to AfterValidator.
    """

    tags: list[str] = _Field(
        default_factory=list,
    )
    scores: list[int] = _Field(
        default_factory=list,
    )


class ValidatedBytes(_ProtoModel):
    """
    ValidatedBytes exercises bytes length constraints.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Token must be at least 16 bytes.
    token: bytes = _Field(
        default=b"",
        description="Token must be at least 16 bytes.",
    )
    # Hash must be exactly 32 bytes.
    hash_: bytes = _Field(
        default=b"",
        description="Hash must be exactly 32 bytes.",
        alias="hash",
    )
    # Payload must be at most 1024 bytes.
    payload: bytes = _Field(
        default=b"",
        description="Payload must be at most 1024 bytes.",
    )
    # Uuid must be a valid 16-byte binary UUID.
    uuid: bytes = _Field(
        default=b"",
        description="Uuid must be a valid 16-byte binary UUID.",
    )


class ValidatedStringContains(_ProtoModel):
    """
    ValidatedStringContains exercises the string.contains constraint.
    """

    # Topic must contain "protobuf".
    topic: str = _Field(
        default="",
        description='Topic must contain "protobuf".',
    )
    # Label must start with "env-" and contain "prod".
    # The contains conflicts with prefix so contains is dropped.
    label: str = _Field(
        default="",
        description='Label must start with "env-" and contain "prod".\nThe contains conflicts with prefix so contains is dropped.',
    )


class ValidatedUser(_ProtoModel):
    """
    A user account.
    """

    class Role(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        VIEWER = ("VIEWER", 1)
        EDITOR = ("EDITOR", 2)
        ADMIN = ("ADMIN", 3)

    # Display name (1–50 characters).
    name: str = _Field(
        default="",
        description="Display name (1–50 characters).",
    )
    # Age in years.
    age: int = _Field(
        default=0,
        description="Age in years.",
    )
    # Contact email address.
    email: str = _Field(
        default="",
        description="Contact email address.",
    )
    role: "ValidatedUser.Role | None" = _Field(default=None)


class ValidatedRequired(_ProtoModel):
    """
    ValidatedRequired exercises required = true on proto3 optional scalar fields
    (where it strips | None) vs. message-typed and plain scalar fields (dropped).
    """

    class Detail(_ProtoModel):
        """
        Detail is a nested message used to test message-typed required handling.
        """

        value: str = _Field(default="")

    # required on proto3 optional scalar: | None stripped, field becomes required.
    required_name: str | None = _Field(
        default=None,
        description="required on proto3 optional scalar: | None stripped, field becomes required.",
    )
    # required on proto3 optional scalar with an additional constraint.
    required_score: int | None = _Field(
        default=None,
        description="required on proto3 optional scalar with an additional constraint.",
    )
    # required on message-typed optional: not translated, emits dropped comment.
    required_detail: "ValidatedRequired.Detail | None" = _Field(
        default=None,
        description="required on message-typed optional: not translated, emits dropped comment.",
    )
    # required on plain proto3 scalar: not translated, emits dropped comment.
    plain_name: str = _Field(
        default="",
        description="required on plain proto3 scalar: not translated, emits dropped comment.",
    )


class ValidatedOneofFormat(_ProtoModel):
    """
    ValidatedOneofFormat exercises an AfterValidator-type constraint (email) on a
    oneof field. In default mode the generated type is
    _Annotated[str, _AfterValidator(_validate_email)] | None, exercising the
    `| None` branch of wrapWithAnnotated. In gen_options mode it becomes
    _Optional[_Annotated[str, _AfterValidator(_validate_email)]], exercising the
    _Optional[...] branch.
    """

    # Must be a valid email address when set.
    email_contact: str | None = _Field(
        default=None,
        description='Must be a valid email address when set.\nOnly one of the fields can be specified with: ["email_contact", "phone_contact"] (oneof contact)',
    )
    phone_contact: str | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["email_contact", "phone_contact"] (oneof contact)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_contact(self) -> "ValidatedOneofFormat":
        _set = [
            f
            for f in ("email_contact", "phone_contact")
            if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'contact': only one field may be set, got {_set!r}"
            )
        return self


class ValidatedConstOptional(_ProtoModel):
    """
    ValidatedConstOptional exercises const constraints on a oneof field, covering
    the `| None` and `_Optional[...]` branches of ConstLiteral handling in
    applyConstraintTypeOverrides (lines 1291-1294 in main.go).
    """

    # Only "fixed" is valid when set.
    fixed_token: str | None = _Field(
        default=None,
        description='Only "fixed" is valid when set.\nOnly one of the fields can be specified with: ["fixed_token", "other_token"] (oneof token_type)',
    )
    other_token: str | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["fixed_token", "other_token"] (oneof token_type)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_token_type(self) -> "ValidatedConstOptional":
        _set = [
            f for f in ("fixed_token", "other_token") if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'token_type': only one field may be set, got {_set!r}"
            )
        return self


class ValidatedFormatsExtended(_ProtoModel):
    """
    ValidatedFormatsExtended exercises additional format validators beyond the
    original six (email, uri, ip, ipv4, ipv6, uuid).
    """

    # Hostname must be a valid DNS hostname.
    hostname: str = _Field(
        default="",
        description="Hostname must be a valid DNS hostname.",
    )
    # UriRef must be a valid URI reference (absolute or relative).
    uri_ref: str = _Field(
        default="",
        description="UriRef must be a valid URI reference (absolute or relative).",
    )
    # Addr must be a valid IP address or hostname.
    addr: str = _Field(
        default="",
        description="Addr must be a valid IP address or hostname.",
    )
    # Tuuid must be a trimmed UUID (32 hex chars, no dashes).
    tuuid: str = _Field(
        default="",
        description="Tuuid must be a trimmed UUID (32 hex chars, no dashes).",
    )
    # Ulid must be a valid ULID.
    ulid: str = _Field(
        default="",
        description="Ulid must be a valid ULID.",
    )
    # Cidr must be a valid IP address with prefix length (host address).
    cidr: str = _Field(
        default="",
        description="Cidr must be a valid IP address with prefix length (host address).",
    )
    # CidrV4 must be a valid IPv4 address with prefix length.
    cidr_v4: str = _Field(
        default="",
        description="CidrV4 must be a valid IPv4 address with prefix length.",
    )
    # CidrV6 must be a valid IPv6 address with prefix length.
    cidr_v6: str = _Field(
        default="",
        description="CidrV6 must be a valid IPv6 address with prefix length.",
    )
    # IpNet must be a valid IP network (host bits must be zero).
    ip_net: str = _Field(
        default="",
        description="IpNet must be a valid IP network (host bits must be zero).",
    )
    # Ipv4Net must be a valid IPv4 network (host bits must be zero).
    ipv4_net: str = _Field(
        default="",
        description="Ipv4Net must be a valid IPv4 network (host bits must be zero).",
    )
    # Ipv6Net must be a valid IPv6 network (host bits must be zero).
    ipv6_net: str = _Field(
        default="",
        description="Ipv6Net must be a valid IPv6 network (host bits must be zero).",
    )
    # Endpoint must be a valid host:port pair.
    endpoint: str = _Field(
        default="",
        description="Endpoint must be a valid host:port pair.",
    )


class ValidatedWellKnownRegex(_ProtoModel):
    """
    ValidatedWellKnownRegex exercises the well_known_regex enum validator.
    """

    # HeaderName must be a valid HTTP header name.
    header_name: str = _Field(
        default="",
        description="HeaderName must be a valid HTTP header name.",
    )
    # HeaderValue must be a valid HTTP header value.
    header_value: str = _Field(
        default="",
        description="HeaderValue must be a valid HTTP header value.",
    )
    # LooseHeader uses well_known_regex with strict=false (strict is not translated).
    loose_header: str = _Field(
        default="",
        description="LooseHeader uses well_known_regex with strict=false (strict is not translated).",
    )


class ValidatedNotContains(_ProtoModel):
    """
    ValidatedNotContains exercises the string.not_contains constraint.
    """

    # Username must not contain "admin".
    username: str = _Field(
        default="",
        description='Username must not contain "admin".',
    )


class ValidatedFloatIn(_ProtoModel):
    """
    ValidatedFloatIn exercises float.in and double.not_in constraints.
    """

    # Ratio must be one of the allowed values.
    ratio: float = _Field(
        default=0.0,
        description="Ratio must be one of the allowed values.",
    )
    # Score must not be a negative sentinel value.
    score: float = _Field(
        default=0.0,
        description="Score must not be a negative sentinel value.",
    )


class ValidatedFloatExamples(_ProtoModel):
    """
    ValidatedFloatExamples exercises float/double/bool/uint32 example annotations.
    """

    # Ratio must be positive with float examples.
    ratio: float = _Field(
        default=0.0,
        description="Ratio must be positive with float examples.",
    )
    # Score must be positive with double examples.
    score: float = _Field(
        default=0.0,
        description="Score must be positive with double examples.",
    )
    # Flag with bool examples.
    flag: bool = _Field(
        default=False,
        description="Flag with bool examples.",
    )
    # Code must be positive with uint32 examples.
    code: int = _Field(
        default=0,
        description="Code must be positive with uint32 examples.",
    )


class ValidatedCEL(_ProtoModel):
    """
    ValidatedCEL exercises basic field-level CEL transpilation.
    """

    # Age must be positive.
    age: int = _Field(
        default=0,
        description="Age must be positive.",
    )


class ValidatedCELField(_ProtoModel):
    """
    ValidatedCELField exercises field-level CEL transpilation.
    """

    # Must be positive.
    age: int = _Field(
        default=0,
        description="Must be positive.",
    )
    # Must start with an uppercase letter.
    name: str = _Field(
        default="",
        description="Must start with an uppercase letter.",
    )
    # Combined: both bool-returning and chained.
    code: str = _Field(
        default="",
        description="Combined: both bool-returning and chained.",
    )


class ValidatedCELMessage(_ProtoModel):
    """
    ValidatedCELMessage exercises message-level cross-field CEL.
    """

    bar: list[str] = _Field(
        default_factory=list,
    )
    baz: list[str] = _Field(
        default_factory=list,
    )


class ValidatedCELHas(_ProtoModel):
    """
    ValidatedCELHas exercises the has() presence macro.
    """

    first_name: str | None = _Field(default=None)
    last_name: str | None = _Field(default=None)


class ValidatedCELCrossField(_ProtoModel):
    """
    ValidatedCELCrossField exercises a cross-field numeric comparison.
    """

    min_val: int = _Field(default=0)
    max_val: int = _Field(default=0)


class ValidatedCELDropped(_ProtoModel):
    """
    ValidatedCELDropped exercises the drop path for unsupported CEL
    (comprehension). The dropped comment must appear in the generated file.
    """

    scores: list[int] = _Field(
        default_factory=list,
    )


class ValidatedCELStringReturn(_ProtoModel):
    """
    ValidatedCELStringReturn exercises a string-returning CEL expression
    (the expression itself is the error message).
    """

    value: int = _Field(default=0)


class ValidatedBytesIP(_ProtoModel):
    """
    ValidatedBytesIP exercises bytes.ip/ipv4/ipv6 binary address validation.
    """

    # Binary IP address (4 bytes for IPv4 or 16 bytes for IPv6).
    ip_addr: bytes = _Field(
        default=b"",
        description="Binary IP address (4 bytes for IPv4 or 16 bytes for IPv6).",
    )
    # Binary IPv4 address (exactly 4 bytes).
    ipv4_addr: bytes = _Field(
        default=b"",
        description="Binary IPv4 address (exactly 4 bytes).",
    )
    # Binary IPv6 address (exactly 16 bytes).
    ipv6_addr: bytes = _Field(
        default=b"",
        description="Binary IPv6 address (exactly 16 bytes).",
    )


class ValidatedRepeatedItems(_ProtoModel):
    """
    ValidatedRepeatedItems exercises repeated.items per-element constraints.
    """

    # Each tag must be 1–32 characters.
    tags: list[str] = _Field(
        default_factory=list,
        description="Each tag must be 1–32 characters.",
    )
    # Each score must be positive.
    scores: list[int] = _Field(
        default_factory=list,
        description="Each score must be positive.",
    )
    # Each email must be a valid email address.
    emails: list[str] = _Field(
        default_factory=list,
        description="Each email must be a valid email address.",
    )


class ValidatedMapConstraints(_ProtoModel):
    """
    ValidatedMapConstraints exercises map.keys and map.values per-entry constraints.
    """

    # Keys must be 1–63 chars; values must be non-empty.
    labels: dict[str, str] = _Field(
        default_factory=dict,
        description="Keys must be 1–63 chars; values must be non-empty.",
    )
    # Values must be positive.
    counters: dict[str, int] = _Field(
        default_factory=dict,
        description="Values must be positive.",
    )
    # Keys must be a valid email; values must match a pattern.
    rules: dict[str, str] = _Field(
        default_factory=dict,
        description="Keys must be a valid email; values must match a pattern.",
    )
    # Must have at least 1 entry; keys must be non-empty (tests min_pairs + keys together).
    tagged: dict[str, str] = _Field(
        default_factory=dict,
        description="Must have at least 1 entry; keys must be non-empty (tests min_pairs + keys together).",
    )
    # Integer keys must be positive (exercises non-string key constraints).
    scores: dict[int, str] = _Field(
        default_factory=dict,
        description="Integer keys must be positive (exercises non-string key constraints).",
    )


class ValidatedIgnore(_ProtoModel):
    """
    ValidatedIgnore exercises ignore = IGNORE_IF_ZERO_VALUE, which opts a field
    out of ConstrainedRequired even when its constraints reject the zero value.
    """

    # Email allows empty string via ignore (not ConstrainedRequired).
    email: str = _Field(
        default="",
        description="Email allows empty string via ignore (not ConstrainedRequired).",
    )
    # Age allows zero via ignore (not ConstrainedRequired).
    age: int = _Field(
        default=0,
        description="Age allows zero via ignore (not ConstrainedRequired).",
    )


class ValidatedStringBytes(_ProtoModel):
    """
    ValidatedStringBytes exercises string.min_bytes/max_bytes/len_bytes constraints.
    """

    # Payload must be at least 1 UTF-8 byte (ConstrainedRequired: min_bytes > 0).
    payload: str = _Field(
        default="",
        description="Payload must be at least 1 UTF-8 byte (ConstrainedRequired: min_bytes > 0).",
    )
    # Token must be exactly 32 UTF-8 bytes (ConstrainedRequired).
    token: str = _Field(
        default="",
        description="Token must be exactly 32 UTF-8 bytes (ConstrainedRequired).",
    )
    # Label has only a max_bytes limit (NOT ConstrainedRequired: "" is 0 bytes ≤ 255).
    label: str = _Field(
        default="",
        description='Label has only a max_bytes limit (NOT ConstrainedRequired: "" is 0 bytes ≤ 255).',
    )
    # Tag exercises min_bytes + max_bytes together (ConstrainedRequired: min_bytes > 0).
    tag: str = _Field(
        default="",
        description="Tag exercises min_bytes + max_bytes together (ConstrainedRequired: min_bytes > 0).",
    )


class ValidatedCELIsEmail(_ProtoModel):
    """
    ValidatedCELIsEmail exercises isEmail() in a CEL expression.
    """

    contact: str = _Field(default="")


class ValidatedCELIsIp(_ProtoModel):
    """
    ValidatedCELIsIp exercises isIp() with optional version argument.
    """

    addr: str = _Field(default="")
    addr_v4: str = _Field(default="")
    addr_v6: str = _Field(default="")


class ValidatedCELIsIpPrefix(_ProtoModel):
    """
    ValidatedCELIsIpPrefix exercises isIpPrefix().
    """

    prefix: str = _Field(default="")
    prefix_v4: str = _Field(default="")


class ValidatedCELIsHostname(_ProtoModel):
    """
    ValidatedCELIsHostname exercises isHostname().
    """

    host: str = _Field(default="")


class ValidatedCELIsUri(_ProtoModel):
    """
    ValidatedCELIsUri exercises isUri() and isUriRef().
    """

    link: str = _Field(default="")
    ref: str = _Field(default="")


class ValidatedCELIsHostAndPort(_ProtoModel):
    """
    ValidatedCELIsHostAndPort exercises isHostAndPort().
    """

    endpoint: str = _Field(default="")


class ValidatedCELIsNanInf(_ProtoModel):
    """
    ValidatedCELIsNanInf exercises isNan() and isInf() in CEL.
    """

    value: float = _Field(default=0.0)
    bounded: float = _Field(default=0.0)


class ValidatedCELAll(_ProtoModel):
    """
    ValidatedCELAll exercises all() comprehension on a repeated field.
    """

    scores: list[int] = _Field(
        default_factory=list,
    )


class ValidatedCELExists(_ProtoModel):
    """
    ValidatedCELExists exercises exists() comprehension.
    """

    tags: list[str] = _Field(
        default_factory=list,
    )


class ValidatedCELExistsOne(_ProtoModel):
    """
    ValidatedCELExistsOne exercises exists_one() comprehension.
    """

    roles: list[str] = _Field(
        default_factory=list,
    )


class ValidatedCELFilter(_ProtoModel):
    """
    ValidatedCELFilter exercises filter() comprehension chained with size().
    """

    values: list[int] = _Field(
        default_factory=list,
    )


class ValidatedCELMapAll(_ProtoModel):
    """
    ValidatedCELMapAll exercises map() chained with all() (nested comprehension).
    """

    words: list[str] = _Field(
        default_factory=list,
    )


class ValidatedCELMessageAll(_ProtoModel):
    """
    ValidatedCELMessageAll exercises all() in a message-level CEL expression.
    """

    prices: list[int] = _Field(
        default_factory=list,
    )
    quantities: list[int] = _Field(
        default_factory=list,
    )


class ValidatedCELStillDropped(_ProtoModel):
    """
    ValidatedCELStillDropped verifies the drop path still works for
    expressions containing 'now' (unsupported temporal).
    """

    created: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTimestamp(_ProtoModel):
    """
    ValidatedCELTimestamp — 'this > now' on a Timestamp field.
    """

    deadline: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELDuration(_ProtoModel):
    """
    ValidatedCELDuration — 'this > duration("0s")' on a Duration field.
    """

    window: ProtoDuration | None = _Field(default=None)


class ValidatedCELDurationRange(_ProtoModel):
    """
    ValidatedCELDurationRange — duration bounded between two literals.
    """

    ttl: ProtoDuration | None = _Field(default=None)


class ValidatedCELTimestampAfter(_ProtoModel):
    """
    ValidatedCELTimestampAfter — timestamp compared to a fixed literal.
    """

    created: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTimestampWindow(_ProtoModel):
    """
    ValidatedCELTimestampWindow — arithmetic: now + duration window.
    """

    expires: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsYear(_ProtoModel):
    """
    ValidatedCELTsYear — getFullYear() returns the 4-digit year.
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsMonth(_ProtoModel):
    """
    ValidatedCELTsMonth — getMonth() is 0-indexed (January == 0).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsDayOfMonth(_ProtoModel):
    """
    ValidatedCELTsDayOfMonth — getDayOfMonth() is 0-indexed (1st == 0).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsDayOfWeek(_ProtoModel):
    """
    ValidatedCELTsDayOfWeek — getDayOfWeek(): Sun=0, Mon=1, …, Sat=6.
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsDayOfYear(_ProtoModel):
    """
    ValidatedCELTsDayOfYear — getDayOfYear() is 0-indexed (Jan 1 == 0).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsHours(_ProtoModel):
    """
    ValidatedCELTsHours — getHours() returns the hour (0–23, UTC).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsMillis(_ProtoModel):
    """
    ValidatedCELTsMillis — getMilliseconds() returns the ms component (0–999).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsHoursUTC(_ProtoModel):
    """
    ValidatedCELTsHoursUTC — getHours("UTC") is equivalent to getHours().
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsHoursTZ(_ProtoModel):
    """
    ValidatedCELTsHoursTZ — getHours("America/New_York") uses IANA timezone.
    2024-01-15T17:00:00Z == 12:00 EST (UTC-5, no DST in January).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELDurGetHours(_ProtoModel):
    """
    ValidatedCELDurGetHours — getHours() returns total hours (truncated).
    """

    d: ProtoDuration | None = _Field(default=None)


class ValidatedCELDurGetMinutes(_ProtoModel):
    """
    ValidatedCELDurGetMinutes — getMinutes() returns total minutes (truncated).
    """

    d: ProtoDuration | None = _Field(default=None)


class ValidatedCELDurGetSeconds(_ProtoModel):
    """
    ValidatedCELDurGetSeconds — getSeconds() returns total seconds (truncated).
    """

    d: ProtoDuration | None = _Field(default=None)


class ValidatedCELDurGetMillis(_ProtoModel):
    """
    ValidatedCELDurGetMillis — getMilliseconds() returns total ms (truncated).
    """

    d: ProtoDuration | None = _Field(default=None)


class ValidatedCELEndsWith(_ProtoModel):
    """
    ValidatedCELEndsWith — endsWith() member function (0% coverage).
    """

    filename: str = _Field(default="")


class ValidatedCELContains(_ProtoModel):
    """
    ValidatedCELContains — contains() member function (0% coverage).
    """

    tag: str = _Field(default="")


class ValidatedCELNegate(_ProtoModel):
    """
    ValidatedCELNegate — unary negate operator; -1 parses as Negate(Literal(1)).
    """

    value: int = _Field(default=0)


class ValidatedCELIndex(_ProtoModel):
    """
    ValidatedCELIndex — index operator this[i] (0% coverage).
    """

    items: list[str] = _Field(
        default_factory=list,
    )


class ValidatedCELInList(_ProtoModel):
    """
    ValidatedCELInList — in operator with list literal (list() 0% coverage).
    """

    role: str = _Field(default="")


class ValidatedCELNullCheck(_ProtoModel):
    """
    ValidatedCELNullCheck — null ident (ident() null case, 0% coverage).
    Message-level: this.name != null → (self.name != None).
    """

    name: str | None = _Field(default=None)


class ValidatedCELUint(_ProtoModel):
    """
    ValidatedCELUint — uint32 field exercises celTypeForKind UintKind and
    the uint64 literal case in literal() (both 0% coverage).
    Use uint literal 0u so the comparison is uint > uint (not uint > int).
    """

    count: int = _Field(default=0)


class ValidatedCELFloatLiteral(_ProtoModel):
    """
    ValidatedCELFloatLiteral — float64 literal (e.g. 0.5) in a CEL expression
    exercises the float64 case in literal() (0% coverage).
    """

    score: float = _Field(default=0.0)


class ValidatedCELGlobalSize(_ProtoModel):
    """
    ValidatedCELGlobalSize — size() as a global call (not member) is 0% covered.
    """

    tags: list[str] = _Field(
        default_factory=list,
    )


class ValidatedCELCastInt(_ProtoModel):
    """
    ValidatedCELCastInt — int() global type-cast (globalFunc int 0% covered).
    """

    fraction: float = _Field(default=0.0)


class ValidatedCELIsInfDir(_ProtoModel):
    """
    ValidatedCELIsInfDir — isInf(direction) 1-arg form (0% covered).
    """

    value: float = _Field(default=0.0)
    magnitude: float = _Field(default=0.0)


class ValidatedCELIsIpPrefixV6(_ProtoModel):
    """
    ValidatedCELIsIpPrefixV6 — isIpPrefix(version) 1-arg form (0% covered).
    """

    prefix: str = _Field(default="")


class ValidatedCELTsDate(_ProtoModel):
    """
    ValidatedCELTsDate — getDate() (1-indexed day; 0% covered).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsMinutes(_ProtoModel):
    """
    ValidatedCELTsMinutes — getMinutes() (0% covered).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELTsSeconds(_ProtoModel):
    """
    ValidatedCELTsSeconds — getSeconds() (0% covered).
    """

    t: ProtoTimestamp | None = _Field(default=None)


class ValidatedCELBool(_ProtoModel):
    """
    ValidatedCELBool — bool field exercises celTypeForKind BoolKind (44.4% fn).
    Also exercises literal() bool case (True path).
    """

    active: bool = _Field(default=False)


class ValidatedCELBytes(_ProtoModel):
    """
    ValidatedCELBytes — bytes field exercises celTypeForKind BytesKind (44.4%).
    """

    data: bytes = _Field(default=b"")


class ValidatedCELMapLiteral(_ProtoModel):
    """
    ValidatedCELMapLiteral — map literal {k:v} covers mapExpr (was 0%).
    """

    role: str = _Field(default="")


class ValidatedCELCastDouble(_ProtoModel):
    """
    ValidatedCELCastDouble — double() covers globalFunc double (was 0%).
    """

    value: int = _Field(default=0)


class ValidatedCELCastString(_ProtoModel):
    """
    ValidatedCELCastString — string() covers globalFunc string (was 0%).
    """

    code: int = _Field(default=0)


class ValidatedCELCastUint(_ProtoModel):
    """
    ValidatedCELCastUint — uint() covers globalFunc uint (was 0%).
    """

    count: int = _Field(default=0)


class ValidatedCELMapField(_ProtoModel):
    """
    ValidatedCELMapField — map<K,V> field covers celFieldKey/celTypeForField
    IsMap branches (both were 0%).
    """

    labels: dict[str, int] = _Field(
        default_factory=dict,
    )


class ValidatedCELEnum(_ProtoModel):
    """
    ValidatedCELEnum — enum field covers celTypeForKind EnumKind (was 44%).
    string(this) also exercises globalFunc string on an enum receiver.
    """

    class Priority(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        LOW = ("LOW", 1)
        HIGH = ("HIGH", 2)

    priority: "ValidatedCELEnum.Priority | None" = _Field(default=None)


class ValidatedCELExprField(_ProtoModel):
    """
    ValidatedCELExprField — field-level cel_expression shorthand on an int32 field.
    """

    age: int = _Field(default=0)


class ValidatedCELExprFieldString(_ProtoModel):
    """
    ValidatedCELExprFieldString — cel_expression shorthand on a string field.
    size() must be > 3 to exercise the string CEL dispatch path.
    """

    label: str = _Field(default="")


class ValidatedCELExprFieldMulti(_ProtoModel):
    """
    ValidatedCELExprFieldMulti — two cel_expression entries on one field;
    verifies that all validators are emitted and enforced independently.
    """

    score: int = _Field(default=0)


class ValidatedCELExprMessage(_ProtoModel):
    """
    ValidatedCELExprMessage — message-level cel_expression cross-field rule.
    Exercises cel_expression on MessageRules.
    """

    min_val: int = _Field(default=0)
    max_val: int = _Field(default=0)


class ValidatedCELExprMessageMulti(_ProtoModel):
    """
    ValidatedCELExprMessageMulti — two message-level cel_expression entries;
    verifies that both @model_validator branches are enforced.
    """

    a: int = _Field(default=0)
    b: int = _Field(default=0)
    c: int = _Field(default=0)


class ValidatedCELExprFieldDropped(_ProtoModel):
    """
    ValidatedCELExprFieldDropped — cel_expression shorthand that cannot be
    transpiled (lowerAscii is an ext.Strings function with no Python mapping).
    Verifies the drop path emits a # buf.validate comment.
    """

    tag: str = _Field(default="")


class ValidatedCELExprMessageDropped(_ProtoModel):
    """
    ValidatedCELExprMessageDropped — message-level cel_expression that cannot
    be transpiled. Verifies the drop path emits a # buf.validate comment.
    """

    name: str = _Field(default="")


class ValidatedCELInsideItems(_ProtoModel):
    """
    ValidatedCELInsideItems — verifies that cel and cel_expression inside
    repeated.items are both surfaced as # buf.validate drop comments rather
    than silently ignored.
    """

    # cel inside repeated.items: dropped with a comment (was silently swallowed).
    scores: list[int] = _Field(
        default_factory=list,
        description="cel inside repeated.items: dropped with a comment (was silently swallowed).",
    )
    # cel_expression inside repeated.items: dropped with a comment (was silent).
    ratings: list[int] = _Field(
        default_factory=list,
        description="cel_expression inside repeated.items: dropped with a comment (was silent).",
    )


class ValidatedCELInsideMapValues(_ProtoModel):
    """
    ValidatedCELInsideMapValues — verifies that cel_expression inside map.values
    is surfaced as a drop comment rather than silently ignored.
    """

    counters: dict[str, int] = _Field(
        default_factory=dict,
    )


class ValidatedCELEnumField(_ProtoModel):
    """
    ValidatedCELEnumField exercises message-level CEL comparisons against
    enum fields using the proto integer number (this.food < 3).
    String-based enums cannot be compared with < directly in Python, so
    the transpiler must emit self.food.number for enum fields.
    """

    class Food(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        BREAD = ("BREAD", 1)
        MILK = ("MILK", 2)
        EGGS = ("EGGS", 3)

    food: "ValidatedCELEnumField.Food | None" = _Field(default=None)


class ValidatedCELEnumAliased(_ProtoModel):
    """
    ValidatedCELEnumAliased exercises message-level CEL on an enum field whose
    proto name is a Python reserved word ("type"), which gets renamed to "type_".
    The enumFieldClassMap must key on the proto name so the CEL lookup works.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    class Kind(_ProtoEnum):
        UNSPECIFIED = ("UNSPECIFIED", 0)
        A = ("A", 1)
        B = ("B", 2)
        C = ("C", 3)

    type_: "ValidatedCELEnumAliased.Kind | None" = _Field(
        default=None,
        alias="type",
    )
