# DO NOT EDIT. Generated by protoc-gen-pydantic.
import datetime as _datetime
import ipaddress as _ipaddress
import math as _math
import re as _re
import uuid as _uuid_lib
from dataclasses import dataclass as _dataclass
from enum import Enum as _Enum
from typing import Any as _Any
from typing import Annotated as _Annotated
from typing import Optional as _Optional

from pydantic import AnyUrl as _AnyUrl
from pydantic import BeforeValidator as _BeforeValidator
from pydantic import PlainSerializer as _PlainSerializer
from pydantic import TypeAdapter as _TypeAdapter

_url_adapter = _TypeAdapter(_AnyUrl)


def _coerce_int(v):
    return int(v)


ProtoInt64 = _Annotated[
    int,
    _BeforeValidator(_coerce_int),
    _PlainSerializer(lambda v: str(v), return_type=str, when_used="json"),
]

ProtoUInt64 = _Annotated[
    int,
    _BeforeValidator(_coerce_int),
    _PlainSerializer(lambda v: str(v), return_type=str, when_used="json"),
]


def _parse_timestamp(v):
    if isinstance(v, str):
        return _datetime.datetime.fromisoformat(v.replace("Z", "+00:00"))
    if isinstance(v, _datetime.datetime):
        return v
    raise ValueError(f"Cannot parse timestamp from {type(v)}")


def _serialize_timestamp(v):
    if v.tzinfo is None:
        v = v.replace(tzinfo=_datetime.timezone.utc)
    s = v.strftime("%Y-%m-%dT%H:%M:%S")
    us = v.microsecond
    if us:
        s += f".{us:06d}".rstrip("0")
    return s + "Z"


ProtoTimestamp = _Annotated[
    _datetime.datetime,
    _BeforeValidator(_parse_timestamp),
    _PlainSerializer(_serialize_timestamp, return_type=str, when_used="json"),
]


def _parse_duration(v):
    if isinstance(v, str):
        m = _re.match(r"^(-?\d+(?:\.\d+)?)s$", v)
        if not m:
            raise ValueError(f"Invalid duration: {v}")
        return _datetime.timedelta(seconds=float(m.group(1)))
    if isinstance(v, _datetime.timedelta):
        return v
    raise ValueError(f"Cannot parse duration from {type(v)}")


def _serialize_duration(v):
    total = v.total_seconds()
    if total == int(total):
        return f"{int(total)}s"
    return f"{total}s"


ProtoDuration = _Annotated[
    _datetime.timedelta,
    _BeforeValidator(_parse_duration),
    _PlainSerializer(_serialize_duration, return_type=str, when_used="json"),
]


def _require_unique(v):
    if len(v) != len(set(v)):
        raise ValueError("list items must be unique")
    return v


def _make_in_validator(valid_values):
    def _validate(v):
        if v not in valid_values:
            raise ValueError(f"value must be one of {sorted(valid_values)}")
        return v

    return _validate


def _make_not_in_validator(excluded_values):
    def _validate(v):
        if v in excluded_values:
            raise ValueError(f"value must not be one of {sorted(excluded_values)}")
        return v

    return _validate


def _make_cel_validator(pred, message: str):
    def _validate(v):
        if not pred(v):
            raise ValueError(message)
        return v

    return _validate


def _make_cel_str_validator(fn):
    def _validate(v):
        msg = fn(v)
        if msg:
            raise ValueError(msg)
        return v

    return _validate


def _is_unique(v) -> bool:
    return len(v) == len(set(v))


def _cel_matches(pattern: str, s: str) -> bool:
    return bool(_re.search(pattern, s))


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    display_name: _Optional[str] = None
    is_default: _Optional[bool] = None
    metadata: _Optional[_Any] = None
    priority: _Optional[int] = None
    rank: _Optional[int] = None
    rate: _Optional[float] = None
    serial: _Optional[int] = None
    version: _Optional[int] = None
    weight: _Optional[float] = None


class _ProtoEnum(int, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _Optional[_EnumValueOptions] = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        obj.number = int(value)
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


def _validate_email(v: str) -> str:
    if not v:
        return v
    from pydantic.networks import validate_email as _pydantic_validate_email

    _pydantic_validate_email(v)
    return v


def _validate_uri(v: str) -> str:
    if not v:
        return v
    _url_adapter.validate_python(v)
    return v


def _validate_ip(v: str) -> str:
    if not v:
        return v
    _ipaddress.ip_address(v)
    return v


def _validate_ipv4(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv4Address(v)
    return v


def _validate_ipv6(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv6Address(v)
    return v


def _validate_uuid(v: str) -> str:
    if not v:
        return v
    _uuid_lib.UUID(v)
    return v


def _require_finite(v: float) -> float:
    if not _math.isfinite(v):
        raise ValueError("value must be finite")
    return v


def _make_const_validator(c):
    def _validate(v):
        if v != c:
            raise ValueError(f"value must equal {c!r}")
        return v

    return _validate


def _validate_hostname(v: str) -> str:
    if not v:
        return v
    if len(v) > 253:
        raise ValueError("invalid hostname: too long")
    labels = v.rstrip(".").split(".")
    for label in labels:
        if not label or len(label) > 63:
            raise ValueError("invalid hostname: label length")
        if label.startswith("-") or label.endswith("-"):
            raise ValueError("invalid hostname: label has leading/trailing hyphen")
        if not _re.fullmatch(r"[A-Za-z0-9-]+", label):
            raise ValueError("invalid hostname: invalid characters")
    if labels[-1].isdigit():
        raise ValueError("invalid hostname: TLD is all-numeric")
    return v


def _validate_uri_ref(v: str) -> str:
    if not v:
        return v
    if _re.search(r"[\x00-\x1f\x7f\s]", v):
        raise ValueError(
            "invalid URI reference: contains control characters or whitespace"
        )
    return v


def _validate_address(v: str) -> str:
    if not v:
        return v
    try:
        _ipaddress.ip_address(v)
        return v
    except ValueError:
        pass
    return _validate_hostname(v)


def _validate_tuuid(v: str) -> str:
    if not v:
        return v
    if not _re.fullmatch(r"[0-9a-fA-F]{32}", v):
        raise ValueError("invalid trimmed UUID: must be 32 hex characters")
    return v


def _validate_ulid(v: str) -> str:
    if not v:
        return v
    if len(v) != 26:
        raise ValueError("invalid ULID: must be 26 characters")
    if not _re.fullmatch(r"[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{26}", v):
        raise ValueError("invalid ULID: invalid characters")
    if v[0].upper() > "7":
        raise ValueError("invalid ULID: timestamp overflow")
    return v


def _validate_ip_with_prefixlen(v: str) -> str:
    if not v:
        return v
    _ipaddress.ip_interface(v)
    return v


def _validate_ipv4_with_prefixlen(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv4Interface(v)
    return v


def _validate_ipv6_with_prefixlen(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv6Interface(v)
    return v


def _validate_ip_prefix(v: str) -> str:
    if not v:
        return v
    _ipaddress.ip_network(v, strict=True)
    return v


def _validate_ipv4_prefix(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv4Network(v, strict=True)
    return v


def _validate_ipv6_prefix(v: str) -> str:
    if not v:
        return v
    _ipaddress.IPv6Network(v, strict=True)
    return v


def _validate_host_and_port(v: str) -> str:
    if not v:
        return v
    if v.startswith("["):
        end = v.find("]")
        if end == -1:
            raise ValueError("invalid host_and_port: unmatched '['")
        host = v[1:end]
        rest = v[end + 1 :]
        if not rest.startswith(":"):
            raise ValueError("invalid host_and_port: missing port after ']'")
        port_str = rest[1:]
        _ipaddress.IPv6Address(host)
    else:
        colon = v.rfind(":")
        if colon == -1:
            raise ValueError("invalid host_and_port: missing port")
        host, port_str = v[:colon], v[colon + 1 :]
        try:
            _ipaddress.IPv4Address(host)
        except ValueError:
            _validate_hostname(host)
    if not port_str.isdigit() or not 0 <= int(port_str) <= 65535:
        raise ValueError(f"invalid port: {port_str!r}")
    return v


def _validate_http_header_name(v: str) -> str:
    if not v:
        return v
    if not _re.fullmatch(r"[!#$%&'*+\-.^_`|~0-9A-Za-z]+", v):
        raise ValueError("invalid HTTP header name")
    return v


def _validate_http_header_value(v: str) -> str:
    if not v:
        return v
    if not _re.fullmatch(r"[\t\x20-\x7e]*", v):
        raise ValueError("invalid HTTP header value")
    return v


def _validate_bytes_uuid(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) != 16:
        raise ValueError("invalid UUID bytes: must be exactly 16 bytes")
    return v


def _validate_bytes_ip(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) not in (4, 16):
        raise ValueError("invalid IP bytes: must be 4 bytes (IPv4) or 16 bytes (IPv6)")
    return v


def _validate_bytes_ipv4(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) != 4:
        raise ValueError("invalid IPv4 bytes: must be exactly 4 bytes")
    return v


def _validate_bytes_ipv6(v: bytes) -> bytes:
    if not v:
        return v
    if len(v) != 16:
        raise ValueError("invalid IPv6 bytes: must be exactly 16 bytes")
    return v


def _make_not_contains_validator(s):
    def _validate(v):
        if s in v:
            raise ValueError(f"value must not contain {s!r}")
        return v

    return _validate


def _make_min_bytes_validator(n):
    def _validate(v):
        b = v.encode()
        if len(b) < n:
            raise ValueError(f"value must be at least {n} bytes, got {len(b)} bytes")
        return v

    return _validate


def _make_max_bytes_validator(n):
    def _validate(v):
        b = v.encode()
        if len(b) > n:
            raise ValueError(f"value must be at most {n} bytes, got {len(b)} bytes")
        return v

    return _validate


def _make_len_bytes_validator(n):
    def _validate(v):
        b = v.encode()
        if len(b) != n:
            raise ValueError(f"value must be exactly {n} bytes, got {len(b)} bytes")
        return v

    return _validate


def _is_email(v: str) -> bool:
    if not v:
        return False
    try:
        from pydantic.networks import validate_email as _pydantic_validate_email

        _pydantic_validate_email(v)
        return True
    except Exception:
        return False


def _is_ip(v: str, version: int) -> bool:
    if not v:
        return False
    try:
        if version == 4:
            _ipaddress.IPv4Address(v)
        elif version == 6:
            _ipaddress.IPv6Address(v)
        else:
            _ipaddress.ip_address(v)
        return True
    except ValueError:
        return False


def _is_ip_prefix(v: str, version: int, *, strict: bool = False) -> bool:
    if not v:
        return False
    try:
        if version == 4:
            _ipaddress.IPv4Network(v, strict=strict)
        elif version == 6:
            _ipaddress.IPv6Network(v, strict=strict)
        else:
            try:
                _ipaddress.IPv6Network(v, strict=strict)
                return True
            except ValueError:
                _ipaddress.IPv4Network(v, strict=strict)
        return True
    except ValueError:
        return False


def _is_hostname(v: str) -> bool:
    if not v:
        return False
    try:
        _validate_hostname(v)
        return True
    except ValueError:
        return False


def _is_uri(v: str) -> bool:
    if not v:
        return False
    try:
        _url_adapter.validate_python(v)
        return True
    except Exception:
        return False


def _is_uri_ref(v: str) -> bool:
    if not v:
        return False
    return not bool(_re.search(r"[\x00-\x1f\x7f\s]", v))


def _is_host_and_port(v: str, requires_port: bool) -> bool:
    if not v:
        return False
    try:
        _validate_host_and_port(v)
        return True
    except ValueError:
        if not requires_port:
            try:
                _validate_hostname(v)
                return True
            except ValueError:
                pass
            try:
                _ipaddress.ip_address(v)
                return True
            except ValueError:
                pass
        return False


def _is_nan(v: float) -> bool:
    return _math.isnan(v)


def _is_inf(v: float, direction: int = 0) -> bool:
    if not _math.isinf(v):
        return False
    if direction > 0:
        return v > 0
    if direction < 0:
        return v < 0
    return True


def _cel_now() -> _datetime.datetime:
    return _datetime.datetime.now(tz=_datetime.timezone.utc)


def _cel_duration(total_seconds: float) -> _datetime.timedelta:
    return _datetime.timedelta(seconds=total_seconds)


def _cel_timestamp(s: str) -> _datetime.datetime:
    return _datetime.datetime.fromisoformat(s.replace("Z", "+00:00"))


def _cel_ts_in_tz(v: _datetime.datetime, tz: str) -> _datetime.datetime:
    if tz == "UTC":
        return v
    try:
        import zoneinfo as _zoneinfo
    except ImportError:
        from backports import zoneinfo as _zoneinfo  # type: ignore[no-redef]
    return v.astimezone(_zoneinfo.ZoneInfo(tz))


def _cel_dur_get_hours(v: _datetime.timedelta) -> int:
    return (v.days * 86400 + v.seconds) // 3600


def _cel_dur_get_minutes(v: _datetime.timedelta) -> int:
    return (v.days * 86400 + v.seconds) // 60


def _cel_dur_get_seconds(v: _datetime.timedelta) -> int:
    return v.days * 86400 + v.seconds


def _cel_dur_get_milliseconds(v: _datetime.timedelta) -> int:
    return v.days * 86400000 + v.seconds * 1000 + v.microseconds // 1000


def _cel_enum_number(cls, val):
    """Return the proto integer number for an enum field value (None → 0)."""
    if val is None:
        return 0
    return cls(val).number
