# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    display_name: _Optional[str] = None
    is_default: _Optional[bool] = None
    priority: _Optional[int] = None
    rank: _Optional[int] = None
    rate: _Optional[float] = None
    serial: _Optional[int] = None
    version: _Optional[int] = None
    weight: _Optional[float] = None


class _ProtoEnum(int, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _Optional[_EnumValueOptions] = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        obj.number = int(value)
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class CommentedMessage(_ProtoModel):
    """
    Leading comment on CommentedMessage.
    CommentedMessage exercises all comment positions.
    """

    class NestedEnum(_ProtoEnum):
        """
        Leading comment on NestedEnum.
        An enum nested inside CommentedMessage.
        """

        # Trailing comment on NestedEnum.
        # Documents the enum values.

        # Leading comment on UNSPECIFIED value.
        NESTED_ENUM_UNSPECIFIED = 0
        # Right comment on UNSPECIFIED.
        # Leading comment on ACTIVE value.
        NESTED_ENUM_ACTIVE = 1
        # Right comment on ACTIVE.
        # Leading comment on INACTIVE value.
        NESTED_ENUM_INACTIVE = 2
        # Right comment on INACTIVE.

    class NestedMessage(_ProtoModel):
        """
        Leading comment on NestedMessage.
        A message nested inside CommentedMessage.
        """

        # Trailing comment on NestedMessage.
        # Documents internal structure.

        # Leading comment on nested first_name.
        # The given name in the nested message.
        firstName: str = _Field(default="")
        # Right comment on nested first_name.
        # Leading comment on nested last_name.
        # The family name in the nested message.
        lastName: str = _Field(default="")
        # Right comment on nested last_name.

    # Trailing comment on CommentedMessage.
    # Documents internal structure.

    # Leading comment on first_name.
    # The given name of the person.
    firstName: str = _Field(default="")
    # Right comment on first_name.
    # Leading comment on last_name.
    # The family name of the person.
    lastName: str = _Field(default="")
    # Right comment on last_name.


class Outer(_ProtoModel):
    """
    Outer message comment.
    """

    class OuterEnum(_ProtoEnum):
        """
        Outer enum comment.
        """

        OUTER_ENUM_UNSPECIFIED = 0
        OUTER_ENUM_X = 1

    class Inner(_ProtoModel):
        """
        Inner message comment.
        """

        class InnerEnum(_ProtoEnum):
            """
            Inner enum comment.
            """

            INNER_ENUM_UNSPECIFIED = 0
            INNER_ENUM_A = 1

        class Deepest(_ProtoModel):
            """
            Deepest message comment.
            """

            # Deepest field comment.
            deepestField: str = _Field(default="")

        # Inner field comment.
        innerField: str = _Field(default="")

    # Outer field comment.
    outerField: str = _Field(default="")
