# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass


@_dataclass(frozen=True)
class _EnumValueOptions:
    number: int
    deprecated: bool = False
    debug_redact: bool = False
    display_name: str | None = None
    is_default: bool | None = None
    priority: int | None = None


class _ProtoEnum(int, _Enum):
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _EnumValueOptions | None = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        if options is not None:
            obj._options_ = options
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Currency(_ProtoEnum):
    """
    Currency enum with custom options.
    """

    CURRENCY_UNSPECIFIED = (
        0,
        _EnumValueOptions(number=0),
    )  # CURRENCY_UNSPECIFIED

    CURRENCY_USD = (
        1,
        _EnumValueOptions(
            number=1,
            display_name="US Dollar",
            is_default=True,
            priority=1,
        ),
    )  # CURRENCY_USD

    CURRENCY_EUR = (
        2,
        _EnumValueOptions(
            number=2,
            display_name="Euro",
            priority=2,
        ),
    )  # CURRENCY_EUR

    CURRENCY_GBP = (
        3,
        _EnumValueOptions(
            number=3,
            display_name="British Pound",
        ),
    )  # CURRENCY_GBP


class Color(int, _Enum):
    """
    Color enum without custom options (regression test).
    """

    COLOR_UNSPECIFIED = 0  # COLOR_UNSPECIFIED

    COLOR_RED = 1  # COLOR_RED

    COLOR_GREEN = 2  # COLOR_GREEN

    COLOR_BLUE = 3  # COLOR_BLUE
