# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from ._proto_types import _EnumValueOptions, _ProtoEnum


class Currency(_ProtoEnum):
    """
    Currency enum with custom options.
    """

    CURRENCY_UNSPECIFIED = 0
    CURRENCY_USD = (
        1,
        _EnumValueOptions(
            display_name="US Dollar",
            is_default=True,
            priority=1,
            rank=1,
            rate=1.5,
            serial=1000,
            version=1,
            weight=1,
        ),
    )
    CURRENCY_EUR = (
        2,
        _EnumValueOptions(
            display_name="Euro",
            is_default=False,
            priority=2,
        ),
    )
    CURRENCY_GBP = (
        3,
        _EnumValueOptions(
            display_name="British Pound",
        ),
    )


class Color(_ProtoEnum):
    """
    Color enum without custom options (regression test).
    """

    COLOR_UNSPECIFIED = 0
    COLOR_RED = 1
    COLOR_GREEN = 2
    COLOR_BLUE = 3
