# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    display_name: _Optional[str] = None
    is_default: _Optional[bool] = None
    priority: _Optional[int] = None
    rank: _Optional[int] = None
    rate: _Optional[float] = None
    serial: _Optional[int] = None
    version: _Optional[int] = None
    weight: _Optional[float] = None


class _ProtoEnum(int, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _Optional[_EnumValueOptions] = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        obj.number = int(value)
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class TaskStatus(_ProtoEnum):
    """
    The current lifecycle status of a task.
    """

    # Not yet assigned a status.
    TASK_STATUS_UNSPECIFIED = 0
    # Task is ready to be worked on.
    TASK_STATUS_OPEN = 1
    # Task has been completed.
    TASK_STATUS_DONE = 2


class User(_ProtoModel):
    """
    A user account in the system.
    Represents a single registered user.
    """

    # The user's display name.
    name: str = _Field(default="")
    # Age in full years.
    age: int = _Field(default=0)
