# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases). Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases). Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class TaskStatus(int, _Enum):
    """
    The current lifecycle status of a task.
    """

    # Not yet assigned a status.
    TASK_STATUS_UNSPECIFIED = 0  # TASK_STATUS_UNSPECIFIED
    # Task is ready to be worked on.
    TASK_STATUS_OPEN = 1  # TASK_STATUS_OPEN
    # Task has been completed.
    TASK_STATUS_DONE = 2  # TASK_STATUS_DONE


class User(_ProtoModel):
    """
    A user account in the system.
    Represents a single registered user.
    """

    # The user's display name.
    name: str = _Field(default="")
    # Age in full years.
    age: int = _Field(default=0)
