# DO NOT EDIT. Generated by protoc-gen-pydantic.

from ._proto_types import _EnumValueOptions, _ProtoEnum


class Tag(_ProtoEnum):
    """
    Tag enum with an Any-typed custom option.
    """

    TAG_UNSPECIFIED = 0
    TAG_ALPHA = (
        1,
        _EnumValueOptions(
            metadata=None,
        ),
    )
    TAG_BETA = 2
