# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


@_dataclass(frozen=True)
class _EnumValueOptions:
    number: int
    deprecated: bool = False
    debug_redact: bool = False
    display_name: str | None = None
    is_default: bool | None = None
    priority: int | None = None
    rank: int | None = None
    rate: float | None = None
    serial: int | None = None
    version: int | None = None
    weight: float | None = None


class _ProtoEnum(int, _Enum):
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _EnumValueOptions | None = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        if options is not None:
            obj._options_ = options
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Enum(int, _Enum):
    ENUM_UNSPECIFIED = 0  # ENUM_UNSPECIFIED
    ENUM_ACTIVE = 1  # ENUM_ACTIVE
    ENUM_INACTIVE = 2  # ENUM_INACTIVE


class Hue(int, _Enum):
    """
    A primary hue.
    """

    HUE_UNSPECIFIED = 0  # HUE_UNSPECIFIED
    HUE_RED = 1  # HUE_RED
    HUE_BLUE = 2  # HUE_BLUE


class Shape(_ProtoModel):
    class Kind(_ProtoEnum):
        KIND_UNSPECIFIED = (
            0,
            _EnumValueOptions(number=0),
        )  # KIND_UNSPECIFIED
        KIND_CIRCLE = (
            1,
            _EnumValueOptions(number=1),
        )  # KIND_CIRCLE
        KIND_SQUARE = (
            2,
            _EnumValueOptions(number=2, deprecated=True),
        )  # KIND_SQUARE

    color: "_Optional[Hue]" = _Field(default=None)
    kind: "_Optional[Shape.Kind]" = _Field(default=None)
