# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from ._proto_types import _EnumValueOptions, _ProtoEnum


class Status(_ProtoEnum):
    """
    Status enum with value options.
    """

    STATUS_UNSPECIFIED = 0
    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 2
    STATUS_ARCHIVED = (
        3,
        _EnumValueOptions(deprecated=True, debug_redact=True),
    )
