# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass


@_dataclass(frozen=True)
class _EnumValueOptions:
    number: int
    deprecated: bool = False
    debug_redact: bool = False


class _ProtoEnum(int, _Enum):
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _EnumValueOptions | None = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        if options is not None:
            obj._options_ = options
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Status(_ProtoEnum):
    """
    Status enum with value options.
    """

    STATUS_UNSPECIFIED = (
        0,
        _EnumValueOptions(number=0),
    )  # STATUS_UNSPECIFIED

    STATUS_ACTIVE = (
        1,
        _EnumValueOptions(number=1),
    )  # STATUS_ACTIVE

    STATUS_INACTIVE = (
        2,
        _EnumValueOptions(number=2),
    )  # STATUS_INACTIVE

    STATUS_ARCHIVED = (
        3,
        _EnumValueOptions(number=3, deprecated=True),
    )  # STATUS_ARCHIVED
