# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from dataclasses import dataclass as _dataclass
from typing import Optional as _Optional


@_dataclass(frozen=True)
class _EnumValueOptions:
    deprecated: bool = False
    debug_redact: bool = False
    display_name: _Optional[str] = None
    is_default: _Optional[bool] = None
    priority: _Optional[int] = None
    rank: _Optional[int] = None
    rate: _Optional[float] = None
    serial: _Optional[int] = None
    version: _Optional[int] = None
    weight: _Optional[float] = None


class _ProtoEnum(int, _Enum):
    number: int
    _options_: _EnumValueOptions

    def __new__(cls, value: int, options: _Optional[_EnumValueOptions] = None):
        obj = int.__new__(cls, value)
        obj._value_ = value
        obj.number = int(value)
        obj._options_ = options if options is not None else _EnumValueOptions()
        return obj

    @property
    def options(self) -> _EnumValueOptions:
        return self._options_


class Status(_ProtoEnum):
    """
    Status enum with value options.
    """

    STATUS_UNSPECIFIED = 0
    STATUS_ACTIVE = 1
    STATUS_INACTIVE = 2
    STATUS_ARCHIVED = (
        3,
        _EnumValueOptions(deprecated=True, debug_redact=True),
    )
