# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum


class Enum(int, _Enum):
    """ """

    ENUM_UNSPECIFIED = 0  # ENUM_UNSPECIFIED

    ENUM_ACTIVE = 1  # ENUM_ACTIVE

    ENUM_INACTIVE = 2  # ENUM_INACTIVE
