# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class Person(_ProtoModel):
    """

    Attributes:
      name (str):
      age (int):
      active (bool):
      score (float):
      avatar (bytes):
    """

    name: "str" = _Field(default="")

    age: "int" = _Field(default=0)

    active: "bool" = _Field(default=False)

    score: "float" = _Field(default=0.0)

    avatar: "bytes" = _Field(default=b"")


class SearchRequest(_ProtoModel):
    """

    Attributes:
      query (_Optional[str]):
      pageSize (_Optional[int]):
      includeDeleted (_Optional[bool]):
    """

    query: "_Optional[str]" = _Field(default=None)

    pageSize: "_Optional[int]" = _Field(default=None)

    includeDeleted: "_Optional[bool]" = _Field(default=None)


class TaggedItem(_ProtoModel):
    """

    Attributes:
      name (str):
      tags (list[str]):
      scores (list[int]):
    """

    name: "str" = _Field(default="")

    tags: "list[str]" = _Field(
        default_factory=list,
    )

    scores: "list[int]" = _Field(
        default_factory=list,
    )


class Config(_ProtoModel):
    """

    Attributes:
      labels (dict[str, str]):
      counters (dict[str, int]):
    """

    labels: "dict[str, str]" = _Field(
        default_factory=dict,
    )

    counters: "dict[str, int]" = _Field(
        default_factory=dict,
    )


class Payment(_ProtoModel):
    """

    Attributes:
      creditCard (_Optional[str]):
      paypal (_Optional[str]):
      bankIban (_Optional[str]):
    """

    creditCard: "_Optional[str]" = _Field(default=None)

    paypal: "_Optional[str]" = _Field(default=None)

    bankIban: "_Optional[str]" = _Field(default=None)


class Address(_ProtoModel):
    """

    Attributes:
      street (str):
      city (str):
    """

    street: "str" = _Field(default="")

    city: "str" = _Field(default="")


class Order(_ProtoModel):
    """

    Attributes:
      orderId (str):
      address (_Optional[Address]):
    """

    orderId: "str" = _Field(default="")

    address: "_Optional[Address]" = _Field(default=None)


class Task(_ProtoModel):
    """

    Attributes:
      statusLabel (str):
      status (_Optional[Task.Status]):
    """

    class Status(int, _Enum):
        """ """

        STATUS_UNSPECIFIED = 0  # STATUS_UNSPECIFIED

        STATUS_OPEN = 1  # STATUS_OPEN

        STATUS_DONE = 2  # STATUS_DONE

    statusLabel: "str" = _Field(default="")

    status: "_Optional[Task.Status]" = _Field(default=None)
