# DO NOT EDIT. Generated by protoc-gen-pydantic.

from typing import Any as _Any, Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoDuration, ProtoInt64, ProtoTimestamp, ProtoUInt64


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class WellKnownTypes(_ProtoModel):
    """

    Attributes:
      wktTimestamp (_Optional[ProtoTimestamp]):
      wktDuration (_Optional[ProtoDuration]):
      wktStruct (_Optional[dict[str, _Any]]):
      wktValue (_Optional[_Any]):
      wktListValue (_Optional[list[_Any]]):
      wktAny (_Optional[_Any]):
      wktFieldMask (_Optional[list[str]]):
      wktBool (_Optional[bool]):
      wktInt32 (_Optional[int]):
      wktInt64 (_Optional[ProtoInt64]):
      wktUint32 (_Optional[int]):
      wktUint64 (_Optional[ProtoUInt64]):
      wktFloat (_Optional[float]):
      wktDouble (_Optional[float]):
      wktString (_Optional[str]):
      wktBytes (_Optional[bytes]):
      wktEmpty (None):
    """

    wktTimestamp: "_Optional[ProtoTimestamp]" = _Field(default=None)

    wktDuration: "_Optional[ProtoDuration]" = _Field(default=None)

    wktStruct: "_Optional[dict[str, _Any]]" = _Field(default=None)

    wktValue: "_Optional[_Any]" = _Field(default=None)

    wktListValue: "_Optional[list[_Any]]" = _Field(default=None)

    wktAny: "_Optional[_Any]" = _Field(default=None)

    wktFieldMask: "_Optional[list[str]]" = _Field(default=None)

    wktBool: "_Optional[bool]" = _Field(default=None)

    wktInt32: "_Optional[int]" = _Field(default=None)

    wktInt64: "_Optional[ProtoInt64]" = _Field(default=None)

    wktUint32: "_Optional[int]" = _Field(default=None)

    wktUint64: "_Optional[ProtoUInt64]" = _Field(default=None)

    wktFloat: "_Optional[float]" = _Field(default=None)

    wktDouble: "_Optional[float]" = _Field(default=None)

    wktString: "_Optional[str]" = _Field(default=None)

    wktBytes: "_Optional[bytes]" = _Field(default=None)

    wktEmpty: "None" = _Field(default=None)
