# DO NOT EDIT. Generated by protoc-gen-pydantic.

from typing import Any as _Any

from pydantic import BaseModel as _BaseModel, Field as _Field

import datetime


class WellKnownTypes(_BaseModel):
    """

    Attributes:
      wkt_timestamp (datetime.datetime):
      wkt_duration (datetime.timedelta):
      wkt_struct (dict[str, _Any]):
      wkt_value (_Any):
      wkt_list_value (list[_Any]):
      wkt_any (_Any):
      wkt_field_mask (list[str]):
      wkt_bool (bool):
      wkt_int32 (int):
      wkt_int64 (int):
      wkt_uint32 (int):
      wkt_uint64 (int):
      wkt_float (float):
      wkt_double (float):
      wkt_string (str):
      wkt_bytes (bytes):
      wkt_empty (None):
    """

    wkt_timestamp: "datetime.datetime" = _Field(...)

    wkt_duration: "datetime.timedelta" = _Field(...)

    wkt_struct: "dict[str, _Any]" = _Field(...)

    wkt_value: "_Any" = _Field(...)

    wkt_list_value: "list[_Any]" = _Field(...)

    wkt_any: "_Any" = _Field(...)

    wkt_field_mask: "list[str]" = _Field(...)

    wkt_bool: "bool" = _Field(...)

    wkt_int32: "int" = _Field(...)

    wkt_int64: "int" = _Field(...)

    wkt_uint32: "int" = _Field(...)

    wkt_uint64: "int" = _Field(...)

    wkt_float: "float" = _Field(...)

    wkt_double: "float" = _Field(...)

    wkt_string: "str" = _Field(...)

    wkt_bytes: "bytes" = _Field(...)

    wkt_empty: "None" = _Field(...)
