# DO NOT EDIT. Generated by protoc-gen-pydantic.

from typing import Any as _Any

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoDuration, ProtoInt64, ProtoTimestamp, ProtoUInt64


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class WellKnownTypes(_ProtoModel):
    """

    Attributes:
      wktTimestamp (ProtoTimestamp | None):
      wktDuration (ProtoDuration | None):
      wktStruct (dict[str, _Any] | None):
      wktValue (_Any | None):
      wktListValue (list[_Any] | None):
      wktAny (_Any | None):
      wktFieldMask (list[str] | None):
      wktBool (bool | None):
      wktInt32 (int | None):
      wktInt64 (ProtoInt64 | None):
      wktUint32 (int | None):
      wktUint64 (ProtoUInt64 | None):
      wktFloat (float | None):
      wktDouble (float | None):
      wktString (str | None):
      wktBytes (bytes | None):
      wktEmpty (None | None):
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    wktTimestamp: "ProtoTimestamp | None" = _Field(None)

    wktDuration: "ProtoDuration | None" = _Field(None)

    wktStruct: "dict[str, _Any] | None" = _Field(None)

    wktValue: "_Any | None" = _Field(None)

    wktListValue: "list[_Any] | None" = _Field(None)

    wktAny: "_Any | None" = _Field(None)

    wktFieldMask: "list[str] | None" = _Field(None)

    wktBool: "bool | None" = _Field(None)

    wktInt32: "int | None" = _Field(None)

    wktInt64: "ProtoInt64 | None" = _Field(None)

    wktUint32: "int | None" = _Field(None)

    wktUint64: "ProtoUInt64 | None" = _Field(None)

    wktFloat: "float | None" = _Field(None)

    wktDouble: "float | None" = _Field(None)

    wktString: "str | None" = _Field(None)

    wktBytes: "bytes | None" = _Field(None)

    wktEmpty: "None | None" = _Field(None)
