# DO NOT EDIT. Generated by protoc-gen-pydantic.
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Shipment(_ProtoModel):
    class Status(_ProtoEnum):
        STATUS_UNSPECIFIED = 0
        STATUS_PENDING = 1
        STATUS_SHIPPED = 2
        STATUS_DELIVERED = 3

    class Item(_ProtoModel):
        sku: str = _Field(default="")
        quantity: int = _Field(default=0)
        price: float = _Field(default=0.0)

    orderId: str = _Field(default="")
    items: "list[Shipment.Item]" = _Field(
        default_factory=list,
    )
    statusNote: str = _Field(default="")
    status: "_Optional[Shipment.Status]" = _Field(default=None)
