# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, Field as _Field


class Outer_OuterEnum(int, _Enum):
    """
    Outer enum comment.
    """

    OUTER_ENUM_UNSPECIFIED = 0  # OUTER_ENUM_UNSPECIFIED

    OUTER_ENUM_X = 1  # OUTER_ENUM_X


class Outer_Inner_InnerEnum(int, _Enum):
    """
    Inner enum comment.
    """

    INNER_ENUM_UNSPECIFIED = 0  # INNER_ENUM_UNSPECIFIED

    INNER_ENUM_A = 1  # INNER_ENUM_A


class Outer_Inner_Deepest(_BaseModel):
    """
    Deepest message comment.

    Attributes:
      deepest_field (str):
        Deepest field comment.
    """

    # Deepest field comment.
    deepest_field: "str" = _Field(...)


class Outer_Inner(_BaseModel):
    """
    Inner message comment.

    Attributes:
      inner_field (str):
        Inner field comment.
    """

    # Inner field comment.
    inner_field: "str" = _Field(...)


class Outer(_BaseModel):
    """
    Outer message comment.

    Attributes:
      outer_field (str):
        Outer field comment.
    """

    # Outer field comment.
    outer_field: "str" = _Field(...)
