# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Outer_OuterEnum(int, _Enum):
    """
    Outer enum comment.
    """

    OUTER_ENUM_UNSPECIFIED = 0  # OUTER_ENUM_UNSPECIFIED

    OUTER_ENUM_X = 1  # OUTER_ENUM_X


class Outer_Inner_InnerEnum(int, _Enum):
    """
    Inner enum comment.
    """

    INNER_ENUM_UNSPECIFIED = 0  # INNER_ENUM_UNSPECIFIED

    INNER_ENUM_A = 1  # INNER_ENUM_A


class Outer_Inner_Deepest(_ProtoModel):
    """
    Deepest message comment.

    Attributes:
      deepestField (str):
        Deepest field comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Deepest field comment.
    deepestField: "str" = _Field("")


class Outer_Inner(_ProtoModel):
    """
    Inner message comment.

    Attributes:
      innerField (str):
        Inner field comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Inner field comment.
    innerField: "str" = _Field("")


class Outer(_ProtoModel):
    """
    Outer message comment.

    Attributes:
      outerField (str):
        Outer field comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Outer field comment.
    outerField: "str" = _Field("")
