# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class Shipment(_ProtoModel):
    class Status(int, _Enum):
        STATUS_UNSPECIFIED = 0  # STATUS_UNSPECIFIED

        STATUS_PENDING = 1  # STATUS_PENDING

        STATUS_SHIPPED = 2  # STATUS_SHIPPED

        STATUS_DELIVERED = 3  # STATUS_DELIVERED

    class Item(_ProtoModel):
        sku: "str" = _Field(default="")

        quantity: "int" = _Field(default=0)

        price: "float" = _Field(default=0.0)

    orderId: "str" = _Field(default="")

    items: "list[Shipment.Item]" = _Field(
        default_factory=list,
    )

    statusNote: "str" = _Field(default="")

    status: "_Optional[Shipment.Status]" = _Field(default=None)
