# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class Outer_OuterEnum(int, _Enum):
    """
    Outer enum comment.
    """

    OUTER_ENUM_UNSPECIFIED = 0  # OUTER_ENUM_UNSPECIFIED

    OUTER_ENUM_X = 1  # OUTER_ENUM_X


class Outer_Inner_InnerEnum(int, _Enum):
    """
    Inner enum comment.
    """

    INNER_ENUM_UNSPECIFIED = 0  # INNER_ENUM_UNSPECIFIED

    INNER_ENUM_A = 1  # INNER_ENUM_A


class Outer_Inner_Deepest(_BaseModel):
    """
    Deepest message comment.

    Attributes:
      deepest_field (str):
        Deepest field comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Deepest field comment.
    deepest_field: "str" = _Field(...)


class Outer_Inner(_BaseModel):
    """
    Inner message comment.

    Attributes:
      inner_field (str):
        Inner field comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Inner field comment.
    inner_field: "str" = _Field(...)


class Outer(_BaseModel):
    """
    Outer message comment.

    Attributes:
      outer_field (str):
        Outer field comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Outer field comment.
    outer_field: "str" = _Field(...)
