# DO NOT EDIT. Generated by protoc-gen-pydantic.
from typing import Optional as _Optional

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Oneofs(_ProtoModel):
    a: _Optional[int] = _Field(default=None)
    b: _Optional[str] = _Field(default=None)

    @_model_validator(mode="after")
    def _validate_oneof_union(self) -> "Oneofs":
        _set = [f for f in ("a", "b") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'union': only one field may be set, got {_set!r}")
        return self


class SingleOneof(_ProtoModel):
    """
    SingleOneof has a oneof with exactly one field, exercising the single-element
    tuple form ("field_name",) in the generated @model_validator.
    """

    theValue: _Optional[int] = _Field(default=None)

    @_model_validator(mode="after")
    def _validate_oneof_choice(self) -> "SingleOneof":
        _set = [f for f in ("the_value",) if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'choice': only one field may be set, got {_set!r}")
        return self
