# DO NOT EDIT. Generated by protoc-gen-pydantic.


from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class ReservedFieldNames(_BaseModel):
    """

    Attributes:
      model_config_ (str):
      model_fields_ (str):
      model_dump_ (str):
    """

    model_config = _ConfigDict(populate_by_name=True)

    model_config_: "str" = _Field(..., alias="model_config")

    model_fields_: "str" = _Field(..., alias="model_fields")

    model_dump_: "str" = _Field(..., alias="model_dump")
