# DO NOT EDIT. Generated by protoc-gen-pydantic.
from typing import Optional as _Optional

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class BuiltinNames(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    bool_: bool = _Field(
        default=False,
        alias="bool",
    )
    float_: float = _Field(
        default=0.0,
        alias="float",
    )
    bytes_: bytes = _Field(
        default=b"",
        alias="bytes",
    )
    int_: int = _Field(
        default=0,
        alias="int",
    )


class ReservedFieldNames(_ProtoModel):
    modelConfig: str = _Field(default="")
    modelFields: str = _Field(default="")
    modelDump: str = _Field(default="")


class ReservedOneof(_ProtoModel):
    """
    ReservedOneof exercises a oneof group where some member names are Python
    reserved words. The validator must use the aliased Python names (bool_,
    float_) in getattr() calls, not the original proto names.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    bool_: _Optional[bool] = _Field(
        default=None,
        alias="bool",
    )
    float_: _Optional[float] = _Field(
        default=None,
        alias="float",
    )
    count: _Optional[int] = _Field(default=None)

    @_model_validator(mode="after")
    def _validate_oneof_value(self) -> "ReservedOneof":
        _set = [f for f in ("bool_", "float_", "count") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'value': only one field may be set, got {_set!r}")
        return self
