# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from typing import Optional as _Optional

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoInt64, ProtoUInt64

from .enums_pydantic import Enum

from .messages_pydantic import Message


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class Scalars_NestedEnum(int, _Enum):
    """ """

    NESTED_ENUM_UNSPECIFIED = 0  # NESTED_ENUM_UNSPECIFIED

    NESTED_ENUM_ACTIVE = 1  # NESTED_ENUM_ACTIVE

    NESTED_ENUM_INACTIVE = 2  # NESTED_ENUM_INACTIVE


class Scalars_NestedMessage(_ProtoModel):
    """

    Attributes:
      firstName (str):
      lastName (str):
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    firstName: "str" = _Field("")

    lastName: "str" = _Field("")


class Scalars(_ProtoModel):
    """

    Attributes:
      int32 (int):
      int64 (ProtoInt64):
      uint32 (int):
      uint64 (ProtoUInt64):
      fixed32 (int):
      fixed64 (ProtoUInt64):
      sint32 (int):
      sint64 (ProtoInt64):
      sfixed32 (int):
      sfixed64 (ProtoInt64):
      bool_ (bool):
      float_ (float):
      double (float):
      string (str):
      bytes_ (bytes):
      enum (_Optional[Enum]):
      nestedEnum (_Optional[Scalars_NestedEnum]):
      message (_Optional[Message]):
      nestedMessage (_Optional[Scalars_NestedMessage]):
      int32Optional (_Optional[int]):
      int64Optional (_Optional[ProtoInt64]):
      uint32Optional (_Optional[int]):
      uint64Optional (_Optional[ProtoUInt64]):
      fixed32Optional (_Optional[int]):
      fixed64Optional (_Optional[ProtoUInt64]):
      sint32Optional (_Optional[int]):
      sint64Optional (_Optional[ProtoInt64]):
      sfixed32Optional (_Optional[int]):
      sfixed64Optional (_Optional[ProtoInt64]):
      boolOptional (_Optional[bool]):
      floatOptional (_Optional[float]):
      doubleOptional (_Optional[float]):
      stringOptional (_Optional[str]):
      bytesOptional (_Optional[bytes]):
      enumOptional (_Optional[Enum]):
      nestedEnumOptional (_Optional[Scalars_NestedEnum]):
      messageOptional (_Optional[Message]):
      nestedMessageOptional (_Optional[Scalars_NestedMessage]):
    """

    model_config = _ConfigDict(
        populate_by_name=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    int32: "int" = _Field(0)

    int64: "ProtoInt64" = _Field(0)

    uint32: "int" = _Field(0)

    uint64: "ProtoUInt64" = _Field(0)

    fixed32: "int" = _Field(0)

    fixed64: "ProtoUInt64" = _Field(0)

    sint32: "int" = _Field(0)

    sint64: "ProtoInt64" = _Field(0)

    sfixed32: "int" = _Field(0)

    sfixed64: "ProtoInt64" = _Field(0)

    bool_: "bool" = _Field(
        False,
        alias="bool",
    )

    float_: "float" = _Field(
        0.0,
        alias="float",
    )

    double: "float" = _Field(0.0)

    string: "str" = _Field("")

    bytes_: "bytes" = _Field(
        b"",
        alias="bytes",
    )

    enum: "_Optional[Enum]" = _Field(None)

    nestedEnum: "_Optional[Scalars_NestedEnum]" = _Field(None)

    message: "_Optional[Message]" = _Field(None)

    nestedMessage: "_Optional[Scalars_NestedMessage]" = _Field(None)

    int32Optional: "_Optional[int]" = _Field(None)

    int64Optional: "_Optional[ProtoInt64]" = _Field(None)

    uint32Optional: "_Optional[int]" = _Field(None)

    uint64Optional: "_Optional[ProtoUInt64]" = _Field(None)

    fixed32Optional: "_Optional[int]" = _Field(None)

    fixed64Optional: "_Optional[ProtoUInt64]" = _Field(None)

    sint32Optional: "_Optional[int]" = _Field(None)

    sint64Optional: "_Optional[ProtoInt64]" = _Field(None)

    sfixed32Optional: "_Optional[int]" = _Field(None)

    sfixed64Optional: "_Optional[ProtoInt64]" = _Field(None)

    boolOptional: "_Optional[bool]" = _Field(None)

    floatOptional: "_Optional[float]" = _Field(None)

    doubleOptional: "_Optional[float]" = _Field(None)

    stringOptional: "_Optional[str]" = _Field(None)

    bytesOptional: "_Optional[bytes]" = _Field(None)

    enumOptional: "_Optional[Enum]" = _Field(None)

    nestedEnumOptional: "_Optional[Scalars_NestedEnum]" = _Field(None)

    messageOptional: "_Optional[Message]" = _Field(None)

    nestedMessageOptional: "_Optional[Scalars_NestedMessage]" = _Field(None)
