# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoInt64, ProtoUInt64

from .enums_pydantic import Enum

from .messages_pydantic import Message


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class Scalars_NestedEnum(int, _Enum):
    """ """

    NESTED_ENUM_UNSPECIFIED = 0  # NESTED_ENUM_UNSPECIFIED

    NESTED_ENUM_ACTIVE = 1  # NESTED_ENUM_ACTIVE

    NESTED_ENUM_INACTIVE = 2  # NESTED_ENUM_INACTIVE


class Scalars_NestedMessage(_ProtoModel):
    """

    Attributes:
      firstName (str):
      lastName (str):
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    firstName: "str" = _Field("")

    lastName: "str" = _Field("")


class Scalars(_ProtoModel):
    """

    Attributes:
      int32 (int):
      int64 (ProtoInt64):
      uint32 (int):
      uint64 (ProtoUInt64):
      fixed32 (int):
      fixed64 (ProtoUInt64):
      sint32 (int):
      sint64 (ProtoInt64):
      sfixed32 (int):
      sfixed64 (ProtoInt64):
      bool_ (bool):
      float_ (float):
      double (float):
      string (str):
      bytes_ (bytes):
      enum (Enum | None):
      nestedEnum (Scalars_NestedEnum | None):
      message (Message | None):
      nestedMessage (Scalars_NestedMessage | None):
      int32Optional (int | None):
      int64Optional (ProtoInt64 | None):
      uint32Optional (int | None):
      uint64Optional (ProtoUInt64 | None):
      fixed32Optional (int | None):
      fixed64Optional (ProtoUInt64 | None):
      sint32Optional (int | None):
      sint64Optional (ProtoInt64 | None):
      sfixed32Optional (int | None):
      sfixed64Optional (ProtoInt64 | None):
      boolOptional (bool | None):
      floatOptional (float | None):
      doubleOptional (float | None):
      stringOptional (str | None):
      bytesOptional (bytes | None):
      enumOptional (Enum | None):
      nestedEnumOptional (Scalars_NestedEnum | None):
      messageOptional (Message | None):
      nestedMessageOptional (Scalars_NestedMessage | None):
    """

    model_config = _ConfigDict(
        populate_by_name=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    int32: "int" = _Field(0)

    int64: "ProtoInt64" = _Field(0)

    uint32: "int" = _Field(0)

    uint64: "ProtoUInt64" = _Field(0)

    fixed32: "int" = _Field(0)

    fixed64: "ProtoUInt64" = _Field(0)

    sint32: "int" = _Field(0)

    sint64: "ProtoInt64" = _Field(0)

    sfixed32: "int" = _Field(0)

    sfixed64: "ProtoInt64" = _Field(0)

    bool_: "bool" = _Field(
        False,
        alias="bool",
    )

    float_: "float" = _Field(
        0.0,
        alias="float",
    )

    double: "float" = _Field(0.0)

    string: "str" = _Field("")

    bytes_: "bytes" = _Field(
        b"",
        alias="bytes",
    )

    enum: "Enum | None" = _Field(None)

    nestedEnum: "Scalars_NestedEnum | None" = _Field(None)

    message: "Message | None" = _Field(None)

    nestedMessage: "Scalars_NestedMessage | None" = _Field(None)

    int32Optional: "int | None" = _Field(None)

    int64Optional: "ProtoInt64 | None" = _Field(None)

    uint32Optional: "int | None" = _Field(None)

    uint64Optional: "ProtoUInt64 | None" = _Field(None)

    fixed32Optional: "int | None" = _Field(None)

    fixed64Optional: "ProtoUInt64 | None" = _Field(None)

    sint32Optional: "int | None" = _Field(None)

    sint64Optional: "ProtoInt64 | None" = _Field(None)

    sfixed32Optional: "int | None" = _Field(None)

    sfixed64Optional: "ProtoInt64 | None" = _Field(None)

    boolOptional: "bool | None" = _Field(None)

    floatOptional: "float | None" = _Field(None)

    doubleOptional: "float | None" = _Field(None)

    stringOptional: "str | None" = _Field(None)

    bytesOptional: "bytes | None" = _Field(None)

    enumOptional: "Enum | None" = _Field(None)

    nestedEnumOptional: "Scalars_NestedEnum | None" = _Field(None)

    messageOptional: "Message | None" = _Field(None)

    nestedMessageOptional: "Scalars_NestedMessage | None" = _Field(None)
