# DO NOT EDIT. Generated by protoc-gen-pydantic.


from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class TreeNode(_ProtoModel):
    """

    Attributes:
      name (str):
      children (list[TreeNode]):
      parent (TreeNode | None):
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    name: "str" = _Field("")

    children: "list[TreeNode]" = _Field(
        default_factory=list,
    )

    parent: "TreeNode | None" = _Field(None)
