# DO NOT EDIT. Generated by protoc-gen-pydantic.


from pydantic import BaseModel as _BaseModel, Field as _Field


class TreeNode(_BaseModel):
    """

    Attributes:
      name (str):
      children (list[TreeNode]):
      parent (TreeNode | None):
    """

    name: "str" = _Field(...)

    children: "list[TreeNode]" = _Field(...)

    parent: "TreeNode | None" = _Field(None)
