# DO NOT EDIT. Generated by protoc-gen-pydantic.
"""
Package: test.api.v1
"""

from enum import Enum as _Enum

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoInt64, ProtoTimestamp, ProtoUInt64

from .enums_pydantic import Enum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Foo_NestedEnum(int, _Enum):
    """
    Enum leading comment.
    Enum leading comment.
    """

    # Enum trailing comment.
    # Enum trailing comment.

    # Enum value leading comment 0.
    NESTED_ENUM_UNSPECIFIED = 0  # NESTED_ENUM_UNSPECIFIED
    # Enum value right comment 0.

    # Enum value leading comment 1.
    NESTED_ENUM_ACTIVE = 1  # NESTED_ENUM_ACTIVE
    # Enum value right comment 1.

    # Enum value leading comment 2.
    NESTED_ENUM_INACTIVE = 2  # NESTED_ENUM_INACTIVE
    # Enum value right comment 2.


class Foo_NestedMessage(_ProtoModel):
    """
    Message leading comment.
    Message leading comment.

    Attributes:
      first_name (str):
        Field leading comment.
        Field leading comment.
      last_name (str):
        Field leading comment.
        Field leading comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Message trailing comment.
    # Message trailing comment.

    # Field leading comment.
    # Field leading comment.
    first_name: "str" = _Field("")
    # Field right comment.

    # Field leading comment.
    # Field leading comment.
    last_name: "str" = _Field("")
    # Field right comment.


class Foo(_ProtoModel):
    """

    Attributes:
      int32 (int):
      int64 (ProtoInt64):
      uint32 (int):
      uint64 (ProtoUInt64):
      fixed32 (int):
      fixed64 (ProtoUInt64):
      sint32 (int):
      sint64 (ProtoInt64):
      sfixed32 (int):
      sfixed64 (ProtoInt64):
      bool_ (bool):
      float_ (float):
      double (float):
      string (str):
      bytes_ (bytes):
      enum (Enum | None):
      nested_enum (Foo_NestedEnum | None):
      message (Message | None):
      nested_message (Foo_NestedMessage | None):
      wkt_timestamp (ProtoTimestamp | None):
      int32_optional (int | None):
      int64_optional (ProtoInt64 | None):
      uint32_optional (int | None):
      uint64_optional (ProtoUInt64 | None):
      fixed32_optional (int | None):
      fixed64_optional (ProtoUInt64 | None):
      sint32_optional (int | None):
      sint64_optional (ProtoInt64 | None):
      sfixed32_optional (int | None):
      sfixed64_optional (ProtoInt64 | None):
      bool_optional (bool | None):
      float_optional (float | None):
      double_optional (float | None):
      string_optional (str | None):
      bytes_optional (bytes | None):
      enum_optional (Enum | None):
      nested_enum_optional (Foo_NestedEnum | None):
      message_optional (Message | None):
      nested_message_optional (Foo_NestedMessage | None):
      wkt_timestamp_optional (ProtoTimestamp | None):
      int32_repeated (list[int]):
      int64_repeated (list[ProtoInt64]):
      uint32_repeated (list[int]):
      uint64_repeated (list[ProtoUInt64]):
      fixed32_repeated (list[int]):
      fixed64_repeated (list[ProtoUInt64]):
      sint32_repeated (list[int]):
      sint64_repeated (list[ProtoInt64]):
      sfixed32_repeated (list[int]):
      sfixed64_repeated (list[ProtoInt64]):
      bool_repeated (list[bool]):
      float_repeated (list[float]):
      double_repeated (list[float]):
      string_repeated (list[str]):
      bytes_repeated (list[bytes]):
      enum_repeated (list[Enum]):
      nested_enum_repeated (list[Foo_NestedEnum]):
      message_repeated (list[Message]):
      nested_message_repeated (list[Foo_NestedMessage]):
      wkt_timestamp_repeated (list[ProtoTimestamp]):
      int32_map_key (dict[int, str]):
      int64_map_key (dict[ProtoInt64, str]):
      uint32_map_key (dict[int, str]):
      uint64_map_key (dict[ProtoUInt64, str]):
      fixed32_map_key (dict[int, str]):
      fixed64_map_key (dict[ProtoUInt64, str]):
      sint32_map_key (dict[int, str]):
      sint64_map_key (dict[ProtoInt64, str]):
      sfixed32_map_key (dict[int, str]):
      sfixed64_map_key (dict[ProtoInt64, str]):
      bool_map_key (dict[bool, str]):
      string_map_key (dict[str, str]):
        map<float, string> float_map_key = 76;
        map<double, string> double_map_key = 77;
      int32_map_value (dict[str, int]):
      int64_map_value (dict[str, ProtoInt64]):
      uint32_map_value (dict[str, int]):
      uint64_map_value (dict[str, ProtoUInt64]):
      fixed32_map_value (dict[str, int]):
      fixed64_map_value (dict[str, ProtoUInt64]):
      sint32_map_value (dict[str, int]):
      sint64_map_value (dict[str, ProtoInt64]):
      sfixed32_map_value (dict[str, int]):
      sfixed64_map_value (dict[str, ProtoInt64]):
      bool_map_value (dict[str, bool]):
      float_map_value (dict[str, float]):
      double_map_value (dict[str, float]):
      string_map_value (dict[str, str]):
      bytes_map_value (dict[str, bytes]):
      enum_map_value (dict[str, Enum]):
      nested_enum_map_value (dict[str, Foo_NestedEnum]):
      message_map_value (dict[str, Message]):
      nested_message_map_value (dict[str, Foo_NestedMessage]):
      wkt_timestamp_map_value (dict[str, ProtoTimestamp]):
      a (int | None):
      b (str | None):
    """

    model_config = _ConfigDict(
        populate_by_name=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    int32: "int" = _Field(0)

    int64: "ProtoInt64" = _Field(0)

    uint32: "int" = _Field(0)

    uint64: "ProtoUInt64" = _Field(0)

    fixed32: "int" = _Field(0)

    fixed64: "ProtoUInt64" = _Field(0)

    sint32: "int" = _Field(0)

    sint64: "ProtoInt64" = _Field(0)

    sfixed32: "int" = _Field(0)

    sfixed64: "ProtoInt64" = _Field(0)

    bool_: "bool" = _Field(
        False,
        alias="bool",
    )

    float_: "float" = _Field(
        0.0,
        alias="float",
    )

    double: "float" = _Field(0.0)

    string: "str" = _Field("")

    bytes_: "bytes" = _Field(
        b"",
        alias="bytes",
    )

    enum: "Enum | None" = _Field(None)

    nested_enum: "Foo_NestedEnum | None" = _Field(None)

    message: "Message | None" = _Field(None)

    nested_message: "Foo_NestedMessage | None" = _Field(None)

    wkt_timestamp: "ProtoTimestamp | None" = _Field(None)

    int32_optional: "int | None" = _Field(None)

    int64_optional: "ProtoInt64 | None" = _Field(None)

    uint32_optional: "int | None" = _Field(None)

    uint64_optional: "ProtoUInt64 | None" = _Field(None)

    fixed32_optional: "int | None" = _Field(None)

    fixed64_optional: "ProtoUInt64 | None" = _Field(None)

    sint32_optional: "int | None" = _Field(None)

    sint64_optional: "ProtoInt64 | None" = _Field(None)

    sfixed32_optional: "int | None" = _Field(None)

    sfixed64_optional: "ProtoInt64 | None" = _Field(None)

    bool_optional: "bool | None" = _Field(None)

    float_optional: "float | None" = _Field(None)

    double_optional: "float | None" = _Field(None)

    string_optional: "str | None" = _Field(None)

    bytes_optional: "bytes | None" = _Field(None)

    enum_optional: "Enum | None" = _Field(None)

    nested_enum_optional: "Foo_NestedEnum | None" = _Field(None)

    message_optional: "Message | None" = _Field(None)

    nested_message_optional: "Foo_NestedMessage | None" = _Field(None)

    wkt_timestamp_optional: "ProtoTimestamp | None" = _Field(None)

    int32_repeated: "list[int]" = _Field(
        default_factory=list,
    )

    int64_repeated: "list[ProtoInt64]" = _Field(
        default_factory=list,
    )

    uint32_repeated: "list[int]" = _Field(
        default_factory=list,
    )

    uint64_repeated: "list[ProtoUInt64]" = _Field(
        default_factory=list,
    )

    fixed32_repeated: "list[int]" = _Field(
        default_factory=list,
    )

    fixed64_repeated: "list[ProtoUInt64]" = _Field(
        default_factory=list,
    )

    sint32_repeated: "list[int]" = _Field(
        default_factory=list,
    )

    sint64_repeated: "list[ProtoInt64]" = _Field(
        default_factory=list,
    )

    sfixed32_repeated: "list[int]" = _Field(
        default_factory=list,
    )

    sfixed64_repeated: "list[ProtoInt64]" = _Field(
        default_factory=list,
    )

    bool_repeated: "list[bool]" = _Field(
        default_factory=list,
    )

    float_repeated: "list[float]" = _Field(
        default_factory=list,
    )

    double_repeated: "list[float]" = _Field(
        default_factory=list,
    )

    string_repeated: "list[str]" = _Field(
        default_factory=list,
    )

    bytes_repeated: "list[bytes]" = _Field(
        default_factory=list,
    )

    enum_repeated: "list[Enum]" = _Field(
        default_factory=list,
    )

    nested_enum_repeated: "list[Foo_NestedEnum]" = _Field(
        default_factory=list,
    )

    message_repeated: "list[Message]" = _Field(
        default_factory=list,
    )

    nested_message_repeated: "list[Foo_NestedMessage]" = _Field(
        default_factory=list,
    )

    wkt_timestamp_repeated: "list[ProtoTimestamp]" = _Field(
        default_factory=list,
    )

    int32_map_key: "dict[int, str]" = _Field(
        default_factory=dict,
    )

    int64_map_key: "dict[ProtoInt64, str]" = _Field(
        default_factory=dict,
    )

    uint32_map_key: "dict[int, str]" = _Field(
        default_factory=dict,
    )

    uint64_map_key: "dict[ProtoUInt64, str]" = _Field(
        default_factory=dict,
    )

    fixed32_map_key: "dict[int, str]" = _Field(
        default_factory=dict,
    )

    fixed64_map_key: "dict[ProtoUInt64, str]" = _Field(
        default_factory=dict,
    )

    sint32_map_key: "dict[int, str]" = _Field(
        default_factory=dict,
    )

    sint64_map_key: "dict[ProtoInt64, str]" = _Field(
        default_factory=dict,
    )

    sfixed32_map_key: "dict[int, str]" = _Field(
        default_factory=dict,
    )

    sfixed64_map_key: "dict[ProtoInt64, str]" = _Field(
        default_factory=dict,
    )

    bool_map_key: "dict[bool, str]" = _Field(
        default_factory=dict,
    )

    # map<float, string> float_map_key = 76;
    # map<double, string> double_map_key = 77;
    string_map_key: "dict[str, str]" = _Field(
        default_factory=dict,
    )
    # map<bytes, string> bytes_map_key = 79;
    # map<Enum, string> enum_map_key = 80;
    # map<NestedEnum, string> nested_enum_map_key = 81;
    # map<Message, string> message_map_key = 82;
    # map<NestedMessage, string> nested_message_map_key = 83;
    # map<google.protobuf.Timestamp, string> wkt_timestamp_map_key = 84;

    int32_map_value: "dict[str, int]" = _Field(
        default_factory=dict,
    )

    int64_map_value: "dict[str, ProtoInt64]" = _Field(
        default_factory=dict,
    )

    uint32_map_value: "dict[str, int]" = _Field(
        default_factory=dict,
    )

    uint64_map_value: "dict[str, ProtoUInt64]" = _Field(
        default_factory=dict,
    )

    fixed32_map_value: "dict[str, int]" = _Field(
        default_factory=dict,
    )

    fixed64_map_value: "dict[str, ProtoUInt64]" = _Field(
        default_factory=dict,
    )

    sint32_map_value: "dict[str, int]" = _Field(
        default_factory=dict,
    )

    sint64_map_value: "dict[str, ProtoInt64]" = _Field(
        default_factory=dict,
    )

    sfixed32_map_value: "dict[str, int]" = _Field(
        default_factory=dict,
    )

    sfixed64_map_value: "dict[str, ProtoInt64]" = _Field(
        default_factory=dict,
    )

    bool_map_value: "dict[str, bool]" = _Field(
        default_factory=dict,
    )

    float_map_value: "dict[str, float]" = _Field(
        default_factory=dict,
    )

    double_map_value: "dict[str, float]" = _Field(
        default_factory=dict,
    )

    string_map_value: "dict[str, str]" = _Field(
        default_factory=dict,
    )

    bytes_map_value: "dict[str, bytes]" = _Field(
        default_factory=dict,
    )

    enum_map_value: "dict[str, Enum]" = _Field(
        default_factory=dict,
    )

    nested_enum_map_value: "dict[str, Foo_NestedEnum]" = _Field(
        default_factory=dict,
    )

    message_map_value: "dict[str, Message]" = _Field(
        default_factory=dict,
    )

    nested_message_map_value: "dict[str, Foo_NestedMessage]" = _Field(
        default_factory=dict,
    )

    wkt_timestamp_map_value: "dict[str, ProtoTimestamp]" = _Field(
        default_factory=dict,
    )

    a: "int | None" = _Field(None)

    b: "str | None" = _Field(None)


class Message(_ProtoModel):
    """
    Message leading comment.
    Message leading comment.

    Attributes:
      first_name (str):
        Field leading comment.
        Field leading comment.
      last_name (str):
        Field leading comment.
        Field leading comment.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Message trailing comment.
    # Message trailing comment.

    # Field leading comment.
    # Field leading comment.
    first_name: "str" = _Field("")
    # Field right comment.

    # Field leading comment.
    # Field leading comment.
    last_name: "str" = _Field("")
    # Field right comment.


class Empty(_ProtoModel):
    """

    Attributes:
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    pass
