# DO NOT EDIT. Generated by protoc-gen-pydantic.


from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoInt64, ProtoUInt64


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    def to_proto_dict(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def to_proto_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (camelCase aliases).
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)

    @classmethod
    def from_proto_dict(cls, data: dict, **kwargs):
        """Deserialize from a dict using ProtoJSON conventions."""
        return cls.model_validate(data, **kwargs)

    @classmethod
    def from_proto_json(cls, json_str: str, **kwargs):
        """Deserialize from a JSON string using ProtoJSON conventions."""
        return cls.model_validate_json(json_str, **kwargs)


class ValidatedScalars(_ProtoModel):
    """
    ValidatedScalars exercises numeric bound constraints.

    Attributes:
      age (int):
        Age must be between 0 and 150 exclusive of 0.
      score (float):
        Score must be in [0.0, 100.0].
      priority (ProtoInt64):
        Priority must be positive.
      ratio (float):
        Ratio must be non-negative and less than 1.
      rank (int):
        Rank must be in [1, 10].
      count (ProtoUInt64 | None):
        Count must be non-zero (covers uint64 / fixed64 literal formatting).
      offset (int | None):
        Offset must be non-negative (covers sint32 / sfixed32 literal formatting).
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Age must be between 0 and 150 exclusive of 0.
    age: "int" = _Field(
        0,
        gt=0,
        le=150,
    )

    # Score must be in [0.0, 100.0].
    score: "float" = _Field(
        0.0,
        ge=0.0,
        le=100.0,
    )

    # Priority must be positive.
    priority: "ProtoInt64" = _Field(
        0,
        gt=0,
    )

    # Ratio must be non-negative and less than 1.
    ratio: "float" = _Field(
        0.0,
        ge=0.0,
        lt=1.0,
    )

    # Rank must be in [1, 10].
    rank: "int" = _Field(
        0,
        ge=1,
        le=10,
    )

    # Count must be non-zero (covers uint64 / fixed64 literal formatting).
    count: "ProtoUInt64 | None" = _Field(
        None,
        gt=0,
    )

    # Offset must be non-negative (covers sint32 / sfixed32 literal formatting).
    offset: "int | None" = _Field(
        None,
        ge=0,
    )


class ValidatedStrings(_ProtoModel):
    """
    ValidatedStrings exercises string length and pattern constraints.

    Attributes:
      name (str):
        Name must be between 1 and 100 characters.
      code (str):
        Code must match uppercase letters only.
      bio (str):
        Bio has only a max length.
      tag (str):
        Tag has only a min length.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Name must be between 1 and 100 characters.
    name: "str" = _Field(
        "",
        min_length=1,
        max_length=100,
    )

    # Code must match uppercase letters only.
    code: "str" = _Field(
        "",
        pattern="^[A-Z]+$",
    )

    # Bio has only a max length.
    bio: "str" = _Field(
        "",
        max_length=500,
    )

    # Tag has only a min length.
    tag: "str" = _Field(
        "",
        min_length=2,
    )


class ValidatedRepeated(_ProtoModel):
    """
    ValidatedRepeated exercises repeated field length constraints.

    Attributes:
      items (list[str]):
        Items must have between 1 and 10 elements.
      tags (list[str]):
        Tags must have at least 1 element.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Items must have between 1 and 10 elements.
    items: "list[str]" = _Field(
        default_factory=list,
        min_length=1,
        max_length=10,
    )

    # Tags must have at least 1 element.
    tags: "list[str]" = _Field(
        default_factory=list,
        min_length=1,
    )


class ValidatedMap(_ProtoModel):
    """
    ValidatedMap exercises map field length constraints.

    Attributes:
      labels (dict[str, str]):
        Labels must have between 1 and 10 entries.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Labels must have between 1 and 10 entries.
    labels: "dict[str, str]" = _Field(
        default_factory=dict,
        min_length=1,
        max_length=10,
    )


class ValidatedReserved(_ProtoModel):
    """
    ValidatedReserved exercises a field whose name is a Python reserved word and
    also carries a buf.validate constraint. The generated field must emit both
    alias= and the constraint kwargs in a single _Field() call.

    Attributes:
      float_ (float):
        Score must be positive.
    """

    model_config = _ConfigDict(
        populate_by_name=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Score must be positive.
    float_: "float" = _Field(
        0.0,
        alias="float",
        gt=0.0,
    )


class ValidatedDropped(_ProtoModel):
    """
    ValidatedDropped exercises constraints that are recognised but not translated.

    Attributes:
      name (str):
        Name is required; the required constraint is not translated.
      tag (str):
        Tag must equal "fixed"; the const constraint is not translated.
    """

    model_config = _ConfigDict(
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    # Name is required; the required constraint is not translated.
    name: "str" = _Field(
        "",
        # buf.validate: required (not translated)
    )

    # Tag must equal "fixed"; the const constraint is not translated.
    tag: "str" = _Field(
        "",
        # buf.validate: const (not translated)
    )
