# DO NOT EDIT. Generated by protoc-gen-pydantic.

from enum import Enum as _Enum
from typing import Annotated as _Annotated, Literal as _Literal, Optional as _Optional

from pydantic import (
    AfterValidator as _AfterValidator,
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import (
    ProtoDuration,
    ProtoInt64,
    ProtoTimestamp,
    ProtoUInt64,
    _cel_matches,
    _is_email,
    _is_host_and_port,
    _is_hostname,
    _is_inf,
    _is_ip,
    _is_ip_prefix,
    _is_nan,
    _is_unique,
    _is_uri,
    _is_uri_ref,
    _make_cel_str_validator,
    _make_cel_validator,
    _make_const_validator,
    _make_in_validator,
    _make_len_bytes_validator,
    _make_max_bytes_validator,
    _make_min_bytes_validator,
    _make_not_contains_validator,
    _make_not_in_validator,
    _require_finite,
    _require_unique,
    _validate_address,
    _validate_bytes_ip,
    _validate_bytes_ipv4,
    _validate_bytes_ipv6,
    _validate_bytes_uuid,
    _validate_email,
    _validate_host_and_port,
    _validate_hostname,
    _validate_http_header_name,
    _validate_http_header_value,
    _validate_ip,
    _validate_ip_prefix,
    _validate_ip_with_prefixlen,
    _validate_ipv4,
    _validate_ipv4_prefix,
    _validate_ipv4_with_prefixlen,
    _validate_ipv6,
    _validate_ipv6_prefix,
    _validate_ipv6_with_prefixlen,
    _validate_tuuid,
    _validate_ulid,
    _validate_uri,
    _validate_uri_ref,
    _validate_uuid,
)


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class ValidatedScalars(_ProtoModel):
    """
    ValidatedScalars exercises numeric bound constraints.
    """

    # Age must be between 0 and 150 exclusive of 0.
    age: int = _Field(
        gt=0,
        le=150,
    )
    # Score must be in [0.0, 100.0].
    score: float = _Field(
        default=0.0,
        ge=0.0,
        le=100.0,
    )
    # Priority must be positive.
    priority: ProtoInt64 = _Field(
        gt=0,
    )
    # Ratio must be non-negative and less than 1.
    ratio: float = _Field(
        default=0.0,
        ge=0.0,
        lt=1.0,
    )
    # Rank must be in [1, 10].
    rank: int = _Field(
        ge=1,
        le=10,
    )
    # Count must be non-zero (covers uint64 / fixed64 literal formatting).
    count: _Optional[ProtoUInt64] = _Field(
        default=None,
        gt=0,
    )
    # Offset must be non-negative (covers sint32 / sfixed32 literal formatting).
    offset: _Optional[int] = _Field(
        default=None,
        ge=0,
    )


class ValidatedStrings(_ProtoModel):
    """
    ValidatedStrings exercises string length and pattern constraints.
    """

    # Name must be between 1 and 100 characters.
    name: str = _Field(
        min_length=1,
        max_length=100,
    )
    # Code must match uppercase letters only.
    code: str = _Field(
        pattern="^[A-Z]+$",
    )
    # Bio has only a max length.
    bio: str = _Field(
        default="",
        max_length=500,
    )
    # Tag has only a min length.
    tag: str = _Field(
        min_length=2,
    )


class ValidatedRepeated(_ProtoModel):
    """
    ValidatedRepeated exercises repeated field length constraints.
    """

    # Items must have between 1 and 10 elements.
    items: list[str] = _Field(
        default_factory=list,
        min_length=1,
        max_length=10,
    )
    # Tags must have at least 1 element.
    tags: list[str] = _Field(
        default_factory=list,
        min_length=1,
    )


class ValidatedMap(_ProtoModel):
    """
    ValidatedMap exercises map field length constraints.
    """

    # Labels must have between 1 and 10 entries.
    labels: dict[str, str] = _Field(
        default_factory=dict,
        min_length=1,
        max_length=10,
    )


class ValidatedReserved(_ProtoModel):
    """
    ValidatedReserved exercises a field whose name is a Python reserved word and
    also carries a buf.validate constraint. The generated field must emit both
    alias= and the constraint kwargs in a single _Field() call.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Score must be positive.
    float_: float = _Field(
        alias="float",
        gt=0.0,
    )


class ValidatedOneof(_ProtoModel):
    """
    ValidatedOneof exercises a oneof field that also carries a constraint.
    """

    # Must be positive when set.
    small: _Optional[int] = _Field(
        default=None,
        gt=0,
    )
    # Must be positive when set.
    large: _Optional[ProtoInt64] = _Field(
        default=None,
        gt=0,
    )

    @_model_validator(mode="after")
    def _validate_oneof_value(self) -> "ValidatedOneof":
        _set = [f for f in ("small", "large") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'value': only one field may be set, got {_set!r}")
        return self


class ValidatedDuration(_ProtoModel):
    """
    ValidatedDuration exercises Duration bound constraints, which use
    message-typed rule fields and cannot be translated to Pydantic Field() args.
    The generator must not panic; instead it emits dropped-constraint comments.
    """

    # Timeout must be positive and at most one hour.
    timeout: _Optional[ProtoDuration] = _Field(
        default=None,
        # buf.validate: gt (not translated)
        # buf.validate: lte (not translated)
    )


class ValidatedTimestamp(_ProtoModel):
    """
    ValidatedTimestamp exercises Timestamp bound constraints, which also use
    message-typed rule fields and must not panic.
    """

    # CreatedAt must be after the Unix epoch.
    createdAt: _Optional[ProtoTimestamp] = _Field(
        default=None,
        # buf.validate: gt (not translated)
    )


class ValidatedStringLen(_ProtoModel):
    """
    ValidatedStringLen exercises the string.len exact-length constraint.
    """

    # Code must be exactly 5 characters.
    code: str = _Field(
        min_length=5,
        max_length=5,
    )


class ValidatedStringAffix(_ProtoModel):
    """
    ValidatedStringAffix exercises string.prefix and string.suffix constraints.
    """

    # Url must start with "https://".
    url: str = _Field(
        pattern="^https://",
    )
    # Filename must end with ".go".
    filename: str = _Field(
        pattern="\\.go$",
    )
    # Path must start with "/home/" and end with ".txt".
    path: str = _Field(
        pattern="^/home/.*\\.txt$",
    )
    # Content must match a pattern; prefix is also set (conflict → prefix dropped).
    content: str = _Field(
        pattern="^[a-z]+$",
        # buf.validate: prefix (not translated)
    )
    # Report must match a pattern; suffix is also set (conflict → suffix dropped).
    report: str = _Field(
        pattern="^report_",
        # buf.validate: suffix (not translated)
    )
    # Notes must match a pattern; contains is also set (conflict → contains dropped).
    notes: str = _Field(
        pattern="^[a-z]+$",
        # buf.validate: contains (not translated)
    )


class ValidatedExamples(_ProtoModel):
    """
    ValidatedExamples exercises the field examples annotation.
    """

    # Count with integer examples.
    count: int = _Field(
        gt=0,
        examples=[1, 42],
    )
    # Name with string examples.
    name: str = _Field(
        min_length=1,
        examples=["alice", "bob"],
    )


class ValidatedFormats(_ProtoModel):
    """
    ValidatedFormats exercises format and semantic validators: email, URI,
    IP address (v4/v6), UUID, and float finite.
    """

    # Email must be a valid email address.
    email: _Annotated[str, _AfterValidator(_validate_email)]
    # Website must be a valid URI.
    website: _Annotated[str, _AfterValidator(_validate_uri)]
    # Address must be a valid IP address.
    address: _Annotated[str, _AfterValidator(_validate_ip)]
    # Ratio must be finite (not inf or NaN).
    ratio: _Annotated[float, _AfterValidator(_require_finite)] = _Field(default=0.0)
    # Token must be a valid UUID.
    token: _Annotated[str, _AfterValidator(_validate_uuid)]
    # Host must be a valid IPv4 address.
    hostV4: _Annotated[str, _AfterValidator(_validate_ipv4)]
    # Host must be a valid IPv6 address.
    hostV6: _Annotated[str, _AfterValidator(_validate_ipv6)]


class ValidatedFinite(_ProtoModel):
    """
    ValidatedFinite exercises float.finite and double.finite constraints.
    """

    # Ratio must be finite (not inf or NaN).
    ratio: _Annotated[float, _AfterValidator(_require_finite)] = _Field(default=0.0)
    # Value must be finite (not inf or NaN).
    value: _Annotated[float, _AfterValidator(_require_finite)] = _Field(default=0.0)


class ValidatedDropped(_ProtoModel):
    """
    ValidatedDropped exercises constraints that are recognised but not translated.
    """

    # Name is required; the required constraint is not translated.
    name: str = _Field(
        default="",
        # buf.validate: required (not translated)
    )
    # Blob has a bytes.const constraint which is not translated (bytes kind unsupported).
    blob: bytes = _Field(
        default=b"",
        # buf.validate: const (not translated)
    )
    # Score must be positive; required is also set but not translated.
    score: int = _Field(
        gt=0,
        # buf.validate: required (not translated)
    )


class ValidatedConst(_ProtoModel):
    """
    ValidatedConst exercises the const constraint translated to Literal[...].
    """

    tag: _Literal["fixed"] = _Field(default="fixed")
    count: _Literal[42] = _Field(default=42)
    active: _Literal[True] = _Field(default=True)
    score: _Annotated[float, _AfterValidator(_make_const_validator(3.14))] = _Field(
        default=3.14,
    )
    code: _Literal[100] = _Field(default=100)
    inactive: _Literal[False] = _Field(default=False)


class ValidatedIn(_ProtoModel):
    """
    ValidatedIn exercises in and not_in constraints translated to AfterValidator.
    """

    status: _Annotated[
        str, _AfterValidator(_make_in_validator(frozenset({"active", "inactive"})))
    ]
    code: _Annotated[
        str, _AfterValidator(_make_not_in_validator(frozenset({"deleted", "archived"})))
    ] = _Field(
        default="",
    )
    priority: _Annotated[int, _AfterValidator(_make_in_validator(frozenset({1, 2, 3})))]
    # Limit covers uint32.in (exercises the uint path in formatScalarLiteral).
    limit: _Annotated[
        int, _AfterValidator(_make_in_validator(frozenset({10, 50, 100})))
    ]


class ValidatedUnique(_ProtoModel):
    """
    ValidatedUnique exercises repeated.unique translated to AfterValidator.
    """

    tags: _Annotated[list[str], _AfterValidator(_require_unique)] = _Field(
        default_factory=list,
    )
    scores: _Annotated[list[int], _AfterValidator(_require_unique)] = _Field(
        default_factory=list,
    )


class ValidatedBytes(_ProtoModel):
    """
    ValidatedBytes exercises bytes length constraints.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # Token must be at least 16 bytes.
    token: bytes = _Field(
        min_length=16,
    )
    # Hash must be exactly 32 bytes.
    hash_: bytes = _Field(
        alias="hash",
        min_length=32,
        max_length=32,
    )
    # Payload must be at most 1024 bytes.
    payload: bytes = _Field(
        default=b"",
        max_length=1024,
    )
    # Uuid must be a valid 16-byte binary UUID.
    uuid: _Annotated[bytes, _AfterValidator(_validate_bytes_uuid)]


class ValidatedStringContains(_ProtoModel):
    """
    ValidatedStringContains exercises the string.contains constraint.
    """

    # Topic must contain "protobuf".
    topic: str = _Field(
        pattern="protobuf",
    )
    # Label must start with "env-" and contain "prod".
    # The contains conflicts with prefix so contains is dropped.
    label: str = _Field(
        pattern="^env-",
        # buf.validate: contains (not translated)
    )


class ValidatedUser(_ProtoModel):
    """
    A user account.
    """

    class Role(int, _Enum):
        ROLE_UNSPECIFIED = 0  # ROLE_UNSPECIFIED
        ROLE_VIEWER = 1  # ROLE_VIEWER
        ROLE_EDITOR = 2  # ROLE_EDITOR
        ROLE_ADMIN = 3  # ROLE_ADMIN

    # Display name (1–50 characters).
    name: str = _Field(
        min_length=1,
        max_length=50,
    )
    # Age in years.
    age: int = _Field(
        default=0,
        ge=0,
    )
    # Contact email address.
    email: _Annotated[str, _AfterValidator(_validate_email)]
    role: "_Optional[ValidatedUser.Role]" = _Field(
        default=None,
        examples=[1],
    )


class ValidatedRequired(_ProtoModel):
    """
    ValidatedRequired exercises required = true on proto3 optional scalar fields
    (where it strips | None) vs. message-typed and plain scalar fields (dropped).
    """

    class Detail(_ProtoModel):
        """
        Detail is a nested message used to test message-typed required handling.
        """

        value: str = _Field(default="")

    # required on proto3 optional scalar: | None stripped, field becomes required.
    requiredName: str = _Field(default=...)
    # required on proto3 optional scalar with an additional constraint.
    requiredScore: int = _Field(
        default=...,
        gt=0,
    )
    # required on message-typed optional: not translated, emits dropped comment.
    requiredDetail: "_Optional[ValidatedRequired.Detail]" = _Field(
        default=None,
        # buf.validate: required (not translated)
    )
    # required on plain proto3 scalar: not translated, emits dropped comment.
    plainName: str = _Field(
        default="",
        # buf.validate: required (not translated)
    )


class ValidatedOneofFormat(_ProtoModel):
    """
    ValidatedOneofFormat exercises an AfterValidator-type constraint (email) on a
    oneof field. In default mode the generated type is
    _Annotated[str, _AfterValidator(_validate_email)] | None, exercising the
    `| None` branch of wrapWithAnnotated. In gen_options mode it becomes
    _Optional[_Annotated[str, _AfterValidator(_validate_email)]], exercising the
    _Optional[...] branch.
    """

    # Must be a valid email address when set.
    emailContact: _Optional[_Annotated[str, _AfterValidator(_validate_email)]] = _Field(
        default=None,
    )
    phoneContact: _Optional[str] = _Field(default=None)

    @_model_validator(mode="after")
    def _validate_oneof_contact(self) -> "ValidatedOneofFormat":
        _set = [
            f
            for f in ("email_contact", "phone_contact")
            if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'contact': only one field may be set, got {_set!r}"
            )
        return self


class ValidatedConstOptional(_ProtoModel):
    """
    ValidatedConstOptional exercises const constraints on a oneof field, covering
    the `| None` and `_Optional[...]` branches of ConstLiteral handling in
    applyConstraintTypeOverrides (lines 1291-1294 in main.go).
    """

    # Only "fixed" is valid when set.
    fixedToken: _Optional[_Literal["fixed"]] = _Field(default=None)
    otherToken: _Optional[str] = _Field(default=None)

    @_model_validator(mode="after")
    def _validate_oneof_token_type(self) -> "ValidatedConstOptional":
        _set = [
            f for f in ("fixed_token", "other_token") if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'token_type': only one field may be set, got {_set!r}"
            )
        return self


class ValidatedFormatsExtended(_ProtoModel):
    """
    ValidatedFormatsExtended exercises additional format validators beyond the
    original six (email, uri, ip, ipv4, ipv6, uuid).
    """

    # Hostname must be a valid DNS hostname.
    hostname: _Annotated[str, _AfterValidator(_validate_hostname)]
    # UriRef must be a valid URI reference (absolute or relative).
    uriRef: _Annotated[str, _AfterValidator(_validate_uri_ref)]
    # Addr must be a valid IP address or hostname.
    addr: _Annotated[str, _AfterValidator(_validate_address)]
    # Tuuid must be a trimmed UUID (32 hex chars, no dashes).
    tuuid: _Annotated[str, _AfterValidator(_validate_tuuid)]
    # Ulid must be a valid ULID.
    ulid: _Annotated[str, _AfterValidator(_validate_ulid)]
    # Cidr must be a valid IP address with prefix length (host address).
    cidr: _Annotated[str, _AfterValidator(_validate_ip_with_prefixlen)]
    # CidrV4 must be a valid IPv4 address with prefix length.
    cidrV4: _Annotated[str, _AfterValidator(_validate_ipv4_with_prefixlen)]
    # CidrV6 must be a valid IPv6 address with prefix length.
    cidrV6: _Annotated[str, _AfterValidator(_validate_ipv6_with_prefixlen)]
    # IpNet must be a valid IP network (host bits must be zero).
    ipNet: _Annotated[str, _AfterValidator(_validate_ip_prefix)]
    # Ipv4Net must be a valid IPv4 network (host bits must be zero).
    ipv4Net: _Annotated[str, _AfterValidator(_validate_ipv4_prefix)]
    # Ipv6Net must be a valid IPv6 network (host bits must be zero).
    ipv6Net: _Annotated[str, _AfterValidator(_validate_ipv6_prefix)]
    # Endpoint must be a valid host:port pair.
    endpoint: _Annotated[str, _AfterValidator(_validate_host_and_port)]


class ValidatedWellKnownRegex(_ProtoModel):
    """
    ValidatedWellKnownRegex exercises the well_known_regex enum validator.
    """

    # HeaderName must be a valid HTTP header name.
    headerName: _Annotated[str, _AfterValidator(_validate_http_header_name)]
    # HeaderValue must be a valid HTTP header value.
    headerValue: _Annotated[str, _AfterValidator(_validate_http_header_value)]
    # LooseHeader uses well_known_regex with strict=false (strict is not translated).
    looseHeader: _Annotated[str, _AfterValidator(_validate_http_header_name)] = _Field(
        # buf.validate: strict=false (not translated)
    )


class ValidatedNotContains(_ProtoModel):
    """
    ValidatedNotContains exercises the string.not_contains constraint.
    """

    # Username must not contain "admin".
    username: _Annotated[
        str, _AfterValidator(_make_not_contains_validator("admin"))
    ] = _Field(
        default="",
    )


class ValidatedFloatIn(_ProtoModel):
    """
    ValidatedFloatIn exercises float.in and double.not_in constraints.
    """

    # Ratio must be one of the allowed values.
    ratio: _Annotated[
        float, _AfterValidator(_make_in_validator(frozenset({0.25, 0.5, 0.75, 1.0})))
    ]
    # Score must not be a negative sentinel value.
    score: _Annotated[
        float, _AfterValidator(_make_not_in_validator(frozenset({-1.0, -2.0})))
    ] = _Field(
        default=0.0,
    )


class ValidatedFloatExamples(_ProtoModel):
    """
    ValidatedFloatExamples exercises float/double/bool/uint32 example annotations.
    """

    # Ratio must be positive with float examples.
    ratio: float = _Field(
        gt=0.0,
        examples=[1.5, 0.25],
    )
    # Score must be positive with double examples.
    score: float = _Field(
        gt=0.0,
        examples=[3.14, 2.71],
    )
    # Flag with bool examples.
    flag: bool = _Field(
        default=False,
        examples=[False, True],
    )
    # Code must be positive with uint32 examples.
    code: int = _Field(
        gt=0,
        examples=[7, 42],
    )


class ValidatedCEL(_ProtoModel):
    """
    ValidatedCEL exercises basic field-level CEL transpilation.
    """

    # Age must be positive.
    age: _Annotated[
        int,
        _AfterValidator(_make_cel_validator(lambda v: v > 0, "age must be positive")),
    ] = _Field(
        default=0,
    )


class ValidatedCELField(_ProtoModel):
    """
    ValidatedCELField exercises field-level CEL transpilation.
    """

    # Must be positive.
    age: _Annotated[
        int,
        _AfterValidator(_make_cel_validator(lambda v: v > 0, "age must be positive")),
    ] = _Field(
        default=0,
    )
    # Must start with an uppercase letter.
    name: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(
                lambda v: _cel_matches("^[A-Z]", v), "name must start with uppercase"
            )
        ),
    ] = _Field(
        default="",
    )
    # Combined: both bool-returning and chained.
    code: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: (v).startswith("X"), "code must start with X")
        ),
        _AfterValidator(
            _make_cel_validator(
                lambda v: len(v) > 2, "code must be longer than 2 chars"
            )
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELMessage(_ProtoModel):
    """
    ValidatedCELMessage exercises message-level cross-field CEL.
    """

    bar: list[str] = _Field(
        default_factory=list,
    )
    baz: list[str] = _Field(
        default_factory=list,
    )

    @_model_validator(mode="after")
    def _validate_cel_globally_unique(self) -> "ValidatedCELMessage":
        if not (_is_unique((self.bar + self.baz))):
            raise ValueError("all values in bar and baz must be globally unique")
        return self


class ValidatedCELHas(_ProtoModel):
    """
    ValidatedCELHas exercises the has() presence macro.
    """

    firstName: _Optional[str] = _Field(default=None)
    lastName: _Optional[str] = _Field(default=None)

    @_model_validator(mode="after")
    def _validate_cel_name_required(self) -> "ValidatedCELHas":
        if not (
            "first_name" in self.model_fields_set
            or "last_name" in self.model_fields_set
        ):
            raise ValueError("at least one name field must be set")
        return self


class ValidatedCELCrossField(_ProtoModel):
    """
    ValidatedCELCrossField exercises a cross-field numeric comparison.
    """

    minVal: int = _Field(default=0)
    maxVal: int = _Field(default=0)

    @_model_validator(mode="after")
    def _validate_cel_min_less_than_max(self) -> "ValidatedCELCrossField":
        if not (self.min_val < self.max_val):
            raise ValueError("min_val must be less than max_val")
        return self


class ValidatedCELDropped(_ProtoModel):
    """
    ValidatedCELDropped exercises the drop path for unsupported CEL
    (comprehension). The dropped comment must appear in the generated file.
    """

    scores: _Annotated[
        list[int],
        _AfterValidator(
            _make_cel_validator(
                lambda v: all((x > 0) for x in v), "all scores must be positive"
            )
        ),
    ] = _Field(
        default_factory=list,
    )


class ValidatedCELStringReturn(_ProtoModel):
    """
    ValidatedCELStringReturn exercises a string-returning CEL expression
    (the expression itself is the error message).
    """

    value: _Annotated[
        int,
        _AfterValidator(
            _make_cel_str_validator(
                lambda v: "" if (v > 0) else "value must be positive"
            )
        ),
    ] = _Field(
        default=0,
    )


class ValidatedBytesIP(_ProtoModel):
    """
    ValidatedBytesIP exercises bytes.ip/ipv4/ipv6 binary address validation.
    """

    # Binary IP address (4 bytes for IPv4 or 16 bytes for IPv6).
    ipAddr: _Annotated[bytes, _AfterValidator(_validate_bytes_ip)]
    # Binary IPv4 address (exactly 4 bytes).
    ipv4Addr: _Annotated[bytes, _AfterValidator(_validate_bytes_ipv4)]
    # Binary IPv6 address (exactly 16 bytes).
    ipv6Addr: _Annotated[bytes, _AfterValidator(_validate_bytes_ipv6)]


class ValidatedRepeatedItems(_ProtoModel):
    """
    ValidatedRepeatedItems exercises repeated.items per-element constraints.
    """

    # Each tag must be 1–32 characters.
    tags: list[_Annotated[str, _Field(min_length=1, max_length=32)]] = _Field(
        default_factory=list,
    )
    # Each score must be positive.
    scores: list[_Annotated[int, _Field(gt=0)]] = _Field(
        default_factory=list,
    )
    # Each email must be a valid email address.
    emails: list[_Annotated[str, _AfterValidator(_validate_email)]] = _Field(
        default_factory=list,
    )


class ValidatedMapConstraints(_ProtoModel):
    """
    ValidatedMapConstraints exercises map.keys and map.values per-entry constraints.
    """

    # Keys must be 1–63 chars; values must be non-empty.
    labels: dict[
        _Annotated[str, _Field(min_length=1, max_length=63)],
        _Annotated[str, _Field(min_length=1)],
    ] = _Field(
        default_factory=dict,
    )
    # Values must be positive.
    counters: dict[str, _Annotated[int, _Field(gt=0)]] = _Field(
        default_factory=dict,
    )
    # Keys must be a valid email; values must match a pattern.
    rules: dict[
        _Annotated[str, _AfterValidator(_validate_email)],
        _Annotated[str, _Field(pattern="^[a-z]+$")],
    ] = _Field(
        default_factory=dict,
    )
    # Must have at least 1 entry; keys must be non-empty (tests min_pairs + keys together).
    tagged: dict[_Annotated[str, _Field(min_length=1)], str] = _Field(
        default_factory=dict,
        min_length=1,
    )
    # Integer keys must be positive (exercises non-string key constraints).
    scores: dict[
        _Annotated[int, _Field(gt=0)],
        _Annotated[str, _AfterValidator(_make_not_in_validator(frozenset({""})))],
    ] = _Field(
        default_factory=dict,
    )


class ValidatedIgnore(_ProtoModel):
    """
    ValidatedIgnore exercises ignore = IGNORE_IF_ZERO_VALUE, which opts a field
    out of ConstrainedRequired even when its constraints reject the zero value.
    """

    # Email allows empty string via ignore (not ConstrainedRequired).
    email: _Annotated[str, _AfterValidator(_validate_email)] = _Field(default="")
    # Age allows zero via ignore (not ConstrainedRequired).
    age: int = _Field(
        default=0,
        gt=0,
    )


class ValidatedStringBytes(_ProtoModel):
    """
    ValidatedStringBytes exercises string.min_bytes/max_bytes/len_bytes constraints.
    """

    # Payload must be at least 1 UTF-8 byte (ConstrainedRequired: min_bytes > 0).
    payload: _Annotated[str, _AfterValidator(_make_min_bytes_validator(1))]
    # Token must be exactly 32 UTF-8 bytes (ConstrainedRequired).
    token: _Annotated[str, _AfterValidator(_make_len_bytes_validator(32))]
    # Label has only a max_bytes limit (NOT ConstrainedRequired: "" is 0 bytes ≤ 255).
    label: _Annotated[str, _AfterValidator(_make_max_bytes_validator(255))] = _Field(
        default="",
    )
    # Tag exercises min_bytes + max_bytes together (ConstrainedRequired: min_bytes > 0).
    tag: _Annotated[
        str,
        _AfterValidator(_make_min_bytes_validator(2)),
        _AfterValidator(_make_max_bytes_validator(64)),
    ]


class ValidatedCELIsEmail(_ProtoModel):
    """
    ValidatedCELIsEmail exercises isEmail() in a CEL expression.
    """

    contact: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: _is_email(v), "contact must be a valid email")
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELIsIp(_ProtoModel):
    """
    ValidatedCELIsIp exercises isIp() with optional version argument.
    """

    addr: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: _is_ip(v, 0), "must be a valid IP address")
        ),
    ] = _Field(
        default="",
    )
    addrV4: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: _is_ip(v, 4), "must be a valid IPv4 address")
        ),
    ] = _Field(
        default="",
    )
    addrV6: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: _is_ip(v, 6), "must be a valid IPv6 address")
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELIsIpPrefix(_ProtoModel):
    """
    ValidatedCELIsIpPrefix exercises isIpPrefix().
    """

    prefix: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(
                lambda v: _is_ip_prefix(v, 0), "must be a valid IP prefix (CIDR)"
            )
        ),
    ] = _Field(
        default="",
    )
    prefixV4: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(
                lambda v: _is_ip_prefix(v, 4, strict=False),
                "must be a valid IPv4 prefix",
            )
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELIsHostname(_ProtoModel):
    """
    ValidatedCELIsHostname exercises isHostname().
    """

    host: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: _is_hostname(v), "must be a valid hostname")
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELIsUri(_ProtoModel):
    """
    ValidatedCELIsUri exercises isUri() and isUriRef().
    """

    link: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(lambda v: _is_uri(v), "must be a valid URI")
        ),
    ] = _Field(
        default="",
    )
    ref: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(
                lambda v: _is_uri_ref(v), "must be a valid URI reference"
            )
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELIsHostAndPort(_ProtoModel):
    """
    ValidatedCELIsHostAndPort exercises isHostAndPort().
    """

    endpoint: _Annotated[
        str,
        _AfterValidator(
            _make_cel_validator(
                lambda v: _is_host_and_port(v, True), "must be a valid host:port"
            )
        ),
    ] = _Field(
        default="",
    )


class ValidatedCELIsNanInf(_ProtoModel):
    """
    ValidatedCELIsNanInf exercises isNan() and isInf() in CEL.
    """

    value: _Annotated[
        float,
        _AfterValidator(
            _make_cel_validator(lambda v: not (_is_nan(v)), "value must not be NaN")
        ),
    ] = _Field(
        default=0.0,
    )
    bounded: _Annotated[
        float,
        _AfterValidator(
            _make_cel_validator(
                lambda v: not (_is_inf(v)), "bounded must not be infinite"
            )
        ),
    ] = _Field(
        default=0.0,
    )


class ValidatedCELAll(_ProtoModel):
    """
    ValidatedCELAll exercises all() comprehension on a repeated field.
    """

    scores: _Annotated[
        list[int],
        _AfterValidator(
            _make_cel_validator(
                lambda v: all((x > 0) for x in v), "all scores must be positive"
            )
        ),
    ] = _Field(
        default_factory=list,
    )


class ValidatedCELExists(_ProtoModel):
    """
    ValidatedCELExists exercises exists() comprehension.
    """

    tags: _Annotated[
        list[str],
        _AfterValidator(
            _make_cel_validator(
                lambda v: any((t == "admin") for t in v), "must include an admin tag"
            )
        ),
    ] = _Field(
        default_factory=list,
    )


class ValidatedCELExistsOne(_ProtoModel):
    """
    ValidatedCELExistsOne exercises exists_one() comprehension.
    """

    roles: _Annotated[
        list[str],
        _AfterValidator(
            _make_cel_validator(
                lambda v: sum(1 for r in v if (r == "admin")) == 1,
                "must have exactly one admin role",
            )
        ),
    ] = _Field(
        default_factory=list,
    )


class ValidatedCELFilter(_ProtoModel):
    """
    ValidatedCELFilter exercises filter() comprehension chained with size().
    """

    values: _Annotated[
        list[int],
        _AfterValidator(
            _make_cel_validator(
                lambda v: len([x for x in v if (x > 0)]) >= 2,
                "must contain at least 2 positive values",
            )
        ),
    ] = _Field(
        default_factory=list,
    )


class ValidatedCELMapAll(_ProtoModel):
    """
    ValidatedCELMapAll exercises map() chained with all() (nested comprehension).
    """

    words: _Annotated[
        list[str],
        _AfterValidator(
            _make_cel_validator(
                lambda v: all((l >= 3) for l in [len(w) for w in v]),
                "all words must be at least 3 characters",
            )
        ),
    ] = _Field(
        default_factory=list,
    )


class ValidatedCELMessageAll(_ProtoModel):
    """
    ValidatedCELMessageAll exercises all() in a message-level CEL expression.
    """

    prices: list[int] = _Field(
        default_factory=list,
    )
    quantities: list[int] = _Field(
        default_factory=list,
    )

    @_model_validator(mode="after")
    def _validate_cel_all_positive(self) -> "ValidatedCELMessageAll":
        if not (
            all((p > 0) for p in self.prices) and all((q > 0) for q in self.quantities)
        ):
            raise ValueError("all prices and quantities must be positive")
        return self


class ValidatedCELStillDropped(_ProtoModel):
    """
    ValidatedCELStillDropped verifies the drop path still works for
    expressions containing 'now' (unsupported temporal).
    """

    created: _Optional[ProtoTimestamp] = _Field(
        default=None,
        # buf.validate: cel id="after_now" (not translated: 'now' not supported)
    )
