# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/custom_options.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'api/v1/custom_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pi/v1/custom_options.proto\x12\x0btest.api.v1\x1a google/protobuf/descriptor.proto*\x92\x01\n\x08\x43urrency\x12\x18\n\x14\x43URRENCY_UNSPECIFIED\x10\x00\x12\'\n\x0c\x43URRENCY_USD\x10\x01\x1a\x15\x92\x82\x19\tUS Dollar\x98\x82\x19\x01\xa0\x82\x19\x01\x12\x1e\n\x0c\x43URRENCY_EUR\x10\x02\x1a\x0c\x92\x82\x19\x04\x45uro\x98\x82\x19\x02\x12#\n\x0c\x43URRENCY_GBP\x10\x03\x1a\x11\x92\x82\x19\rBritish Pound*N\n\x05\x43olor\x12\x15\n\x11\x43OLOR_UNSPECIFIED\x10\x00\x12\r\n\tCOLOR_RED\x10\x01\x12\x0f\n\x0b\x43OLOR_GREEN\x10\x02\x12\x0e\n\nCOLOR_BLUE\x10\x03:I\n\x0c\x64isplay_name\x12!.google.protobuf.EnumValueOptions\x18\xa2\x90\x03 \x01(\tR\x0b\x64isplayName\x88\x01\x01:B\n\x08priority\x12!.google.protobuf.EnumValueOptions\x18\xa3\x90\x03 \x01(\x05R\x08priority\x88\x01\x01:E\n\nis_default\x12!.google.protobuf.EnumValueOptions\x18\xa4\x90\x03 \x01(\x08R\tisDefault\x88\x01\x01\x42\xa5\x01\n\x0f\x63om.test.api.v1B\x12\x43ustomOptionsProtoP\x01Z0github.com/cjermain/protoc-gen-pydantic/test/api\xa2\x02\x03TAX\xaa\x02\x0bTest.Api.V1\xca\x02\x0bTest\\Api\\V1\xe2\x02\x17Test\\Api\\V1\\GPBMetadata\xea\x02\rTest::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.custom_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.test.api.v1B\022CustomOptionsProtoP\001Z0github.com/cjermain/protoc-gen-pydantic/test/api\242\002\003TAX\252\002\013Test.Api.V1\312\002\013Test\\Api\\V1\342\002\027Test\\Api\\V1\\GPBMetadata\352\002\rTest::Api::V1'
  _globals['_CURRENCY'].values_by_name["CURRENCY_USD"]._loaded_options = None
  _globals['_CURRENCY'].values_by_name["CURRENCY_USD"]._serialized_options = b'\222\202\031\tUS Dollar\230\202\031\001\240\202\031\001'
  _globals['_CURRENCY'].values_by_name["CURRENCY_EUR"]._loaded_options = None
  _globals['_CURRENCY'].values_by_name["CURRENCY_EUR"]._serialized_options = b'\222\202\031\004Euro\230\202\031\002'
  _globals['_CURRENCY'].values_by_name["CURRENCY_GBP"]._loaded_options = None
  _globals['_CURRENCY'].values_by_name["CURRENCY_GBP"]._serialized_options = b'\222\202\031\rBritish Pound'
  _globals['_CURRENCY']._serialized_start=79
  _globals['_CURRENCY']._serialized_end=225
  _globals['_COLOR']._serialized_start=227
  _globals['_COLOR']._serialized_end=305
# @@protoc_insertion_point(module_scope)
