# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/enum_options.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'api/v1/enum_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/v1/enum_options.proto\x12\x0btest.api.v1*a\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_INACTIVE\x10\x02\x12\x17\n\x0fSTATUS_ARCHIVED\x10\x03\x1a\x02\x08\x01\x42\xa3\x01\n\x0f\x63om.test.api.v1B\x10\x45numOptionsProtoP\x01Z0github.com/cjermain/protoc-gen-pydantic/test/api\xa2\x02\x03TAX\xaa\x02\x0bTest.Api.V1\xca\x02\x0bTest\\Api\\V1\xe2\x02\x17Test\\Api\\V1\\GPBMetadata\xea\x02\rTest::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.enum_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.test.api.v1B\020EnumOptionsProtoP\001Z0github.com/cjermain/protoc-gen-pydantic/test/api\242\002\003TAX\252\002\013Test.Api.V1\312\002\013Test\\Api\\V1\342\002\027Test\\Api\\V1\\GPBMetadata\352\002\rTest::Api::V1'
  _globals['_STATUS'].values_by_name["STATUS_ARCHIVED"]._loaded_options = None
  _globals['_STATUS'].values_by_name["STATUS_ARCHIVED"]._serialized_options = b'\010\001'
  _globals['_STATUS']._serialized_start=42
  _globals['_STATUS']._serialized_end=139
# @@protoc_insertion_point(module_scope)
