# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/nested_comments.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'api/v1/nested_comments.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pi/v1/nested_comments.proto\x12\x0btest.api.v1\"\xf9\x01\n\x05Outer\x12\x1f\n\x0bouter_field\x18\x01 \x01(\tR\nouterField\x1a\x93\x01\n\x05Inner\x12\x1f\n\x0binner_field\x18\x01 \x01(\tR\ninnerField\x1a.\n\x07\x44\x65\x65pest\x12#\n\rdeepest_field\x18\x01 \x01(\tR\x0c\x64\x65\x65pestField\"9\n\tInnerEnum\x12\x1a\n\x16INNER_ENUM_UNSPECIFIED\x10\x00\x12\x10\n\x0cINNER_ENUM_A\x10\x01\"9\n\tOuterEnum\x12\x1a\n\x16OUTER_ENUM_UNSPECIFIED\x10\x00\x12\x10\n\x0cOUTER_ENUM_X\x10\x01\x42\xa6\x01\n\x0f\x63om.test.api.v1B\x13NestedCommentsProtoP\x01Z0github.com/cjermain/protoc-gen-pydantic/test/api\xa2\x02\x03TAX\xaa\x02\x0bTest.Api.V1\xca\x02\x0bTest\\Api\\V1\xe2\x02\x17Test\\Api\\V1\\GPBMetadata\xea\x02\rTest::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.nested_comments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.test.api.v1B\023NestedCommentsProtoP\001Z0github.com/cjermain/protoc-gen-pydantic/test/api\242\002\003TAX\252\002\013Test.Api.V1\312\002\013Test\\Api\\V1\342\002\027Test\\Api\\V1\\GPBMetadata\352\002\rTest::Api::V1'
  _globals['_OUTER']._serialized_start=46
  _globals['_OUTER']._serialized_end=295
  _globals['_OUTER_INNER']._serialized_start=89
  _globals['_OUTER_INNER']._serialized_end=236
  _globals['_OUTER_INNER_DEEPEST']._serialized_start=131
  _globals['_OUTER_INNER_DEEPEST']._serialized_end=177
  _globals['_OUTER_INNER_INNERENUM']._serialized_start=179
  _globals['_OUTER_INNER_INNERENUM']._serialized_end=236
  _globals['_OUTER_OUTERENUM']._serialized_start=238
  _globals['_OUTER_OUTERENUM']._serialized_end=295
# @@protoc_insertion_point(module_scope)
