# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/reserved_names.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'api/v1/reserved_names.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pi/v1/reserved_names.proto\x12\x0btest.api.v1\"y\n\x12ReservedFieldNames\x12!\n\x0cmodel_config\x18\x01 \x01(\tR\x0bmodelConfig\x12!\n\x0cmodel_fields\x18\x02 \x01(\tR\x0bmodelFields\x12\x1d\n\nmodel_dump\x18\x03 \x01(\tR\tmodelDumpB\xa5\x01\n\x0f\x63om.test.api.v1B\x12ReservedNamesProtoP\x01Z0github.com/cjermain/protoc-gen-pydantic/test/api\xa2\x02\x03TAX\xaa\x02\x0bTest.Api.V1\xca\x02\x0bTest\\Api\\V1\xe2\x02\x17Test\\Api\\V1\\GPBMetadata\xea\x02\rTest::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.reserved_names_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.test.api.v1B\022ReservedNamesProtoP\001Z0github.com/cjermain/protoc-gen-pydantic/test/api\242\002\003TAX\252\002\013Test.Api.V1\312\002\013Test\\Api\\V1\342\002\027Test\\Api\\V1\\GPBMetadata\352\002\rTest::Api::V1'
  _globals['_RESERVEDFIELDNAMES']._serialized_start=44
  _globals['_RESERVEDFIELDNAMES']._serialized_end=165
# @@protoc_insertion_point(module_scope)
