# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/self_reference.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'api/v1/self_reference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pi/v1/self_reference.proto\x12\x0btest.api.v1\"\x90\x01\n\x08TreeNode\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x31\n\x08\x63hildren\x18\x02 \x03(\x0b\x32\x15.test.api.v1.TreeNodeR\x08\x63hildren\x12\x32\n\x06parent\x18\x03 \x01(\x0b\x32\x15.test.api.v1.TreeNodeH\x00R\x06parent\x88\x01\x01\x42\t\n\x07_parentB\xa5\x01\n\x0f\x63om.test.api.v1B\x12SelfReferenceProtoP\x01Z0github.com/cjermain/protoc-gen-pydantic/test/api\xa2\x02\x03TAX\xaa\x02\x0bTest.Api.V1\xca\x02\x0bTest\\Api\\V1\xe2\x02\x17Test\\Api\\V1\\GPBMetadata\xea\x02\rTest::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.self_reference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.test.api.v1B\022SelfReferenceProtoP\001Z0github.com/cjermain/protoc-gen-pydantic/test/api\242\002\003TAX\252\002\013Test.Api.V1\312\002\013Test\\Api\\V1\342\002\027Test\\Api\\V1\\GPBMetadata\352\002\rTest::Api::V1'
  _globals['_TREENODE']._serialized_start=45
  _globals['_TREENODE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
